### ISSUE TITLE
save list

### ISSUE THREAD

**Issue by mahramane** [Tlaster/PreCompose#100]
Hi
I have a LazyColumn that show a list returned from viewmodel.
I want when go to other scene, the list saveed and when goBack to current scene, the list restored.
How can i do this?

**Comment by Tlaster** [comment]
You can define you list in viewmodel and that should be fine.

**Comment by mahramane** [comment]
it didn't work :(
please give me an example

**Comment by Tlaster** [comment]
I think it would be better to share your code and see where the issue is. Or you can check out the [example](https://github.com/Tlaster/PreCompose/blob/f9ba60092c1a203e9fe918f789cad3707a3c2aee/sample/todo/common/src/commonMain/kotlin/moe/tlaster/common/viewmodel/NoteEditViewModel.kt#L19)

**Comment by mahramane** [comment]
This is my view model

```
class BusinessViewModel(private val userRepository: UserRepository) : ViewModel() {

    val businessData: MutableState<State<BusinessData>> = mutableStateOf(State.Loading)
    val businessList: SnapshotStateList<BusinessItems> = mutableStateListOf()


    init {
        getBusinessData()
    }

    fun getBusinessData() {
        viewModelScope.launch {
            userRepository.getBusinessData().onStart {
                businessData.value = State.Loading
            }.catch {
                businessData.value = State.Error("Error 1.", MyHttpStatusCode.NetworkError)
            }.collect {
                businessData.value = when (it.status) {
                    MyHttpStatusCode.Success -> {
                        try {
                            State.Success(it.body(), it.status)
                        } catch (ex: Exception) {
                            State.Error("Error 2", MyHttpStatusCode.ConvertDataError)
                        }
                    }

                    MyHttpStatusCode.InvalidUser -> {
                        State.Error("Error 3", it.status)
                    }

                    else -> {
                        State.Error("Error 4", it.status)
                    }
                }
            }
        }
    }

}
```


this is my compose scene :

```
@Composable
fun BusinessScene(
    viewModel: BusinessViewModel = koinInject(),
) {

    val businessData by remember { viewModel.businessData }
    val businessList = remember { viewModel.businessList }


    LaunchedEffect(businessData) {
        when (businessData) {
            is State.Empty -> {}
            is State.Loading -> {
                if (businessList.isNotEmpty())
                    isPullRefreshing.value = true
            }

            is State.Success -> {
                isPullRefreshing.value = false
                val success = businessData as State.Success<BusinessData>

                businessList.clear()
                businessList.addAll(success.data.businessList)
            }

            is State.Error -> {
                isPullRefreshing.value = false
                val error = businessData as State.Error

                if (businessList.isNotEmpty()) {
                    sceneData.mySnackBar.showSnackBar(error.msg, SnackBarType.ERROR, SnackbarDuration.Long)
                }

                if (error.status == MyHttpStatusCode.InvalidUser) {
                    sceneHelper.signOut(sceneData.navigator)
                }
            }
        }
    }
  }
```

Now i want when from BusinessScene navigate to other Scene and goBack to BusinessScene 
businessList  (`val businessList = remember { viewModel.businessList }`) save its value 
please guide me

**Comment by Tlaster** [comment]
I think the issue is that you clear the list in `LaunchedEffect` every time your `businessData` is success.
Have you try set the `businessList` from your viewmodel's `getBusinessData`?

**Comment by mahramane** [comment]
No that is not the issue because when i open BusinessScene, the businessList will fill. then i navigate to other scene and goBack to BusinessScene, first Loading will run then Sucess (clear list), i want to before run success, businessList have old data.

**Comment by Tlaster** [comment]
Ok I just saw you're using `viewModel: BusinessViewModel = koinInject()`, you might need something like [this](https://github.com/mori-atsushi/koject/blob/c22286b39a3e6249842d148ff0a22f1fb7d37d47/compose/koject-compose-viewmodel/src/main/kotlin/com/moriatsushi/koject/compose/viewmodel/InjectViewModel.kt#L32) in order to use viewmodel with DI, it's from koject but koin should have a similar way to do it.

**Comment by mahramane** [comment]
But that is only for android :')
How can i use that for compose multiplatform?

**Comment by Tlaster** [comment]
Currently not koin or precompose provide such interop method, you can do it your own.

**Comment by Tlaster** [comment]
I'm going to add Koin interop for a easier usage #112

**Comment by mahramane** [comment]
Excellent 👌

**Comment by mahramane** [comment]
in version 1.5.0 this issue was resolved.
Thank you.
