### ISSUE TITLE
[IOS] when camera disappear, my other screen will auto closed, just leave the root screen.

### ISSUE THREAD

**Issue by NakiriYuuzu** [Tlaster/PreCompose#108]
Hi, my problem is When I open the camera, it automatically closes all my screens except the root screen. But i remember the old version[1.4.0] is working fine.

Compose Version: 1.5.0-rc01
Kotlin Version: 1.9.0
Gradle Version: 8.1.1
Precompose Version: 1.5.0-rc01

This is the Repository https://github.com/NakiriYuuzu/DebugKmm

**Comment by hellomr3** [comment]
Hello, how did you fix this. I'm having the same issue
