### ISSUE TITLE
Viewmodel being recreated on back navigation

### ISSUE THREAD

**Issue by JoaoPint0** [Tlaster/PreCompose#110]
So I have this simple use case, a counter increases the values updates the viewmodel and updates the repository when I navigate forward and then back I was expecting the viewmodel not to be recreated.

Am I missing something ? I made a sample project to help clarify if needed https://github.com/JoaoPint0/Koin-Compose-Multiplatfform

```@Composable
fun ActivityRoute(
    navigateToDetails: () -> Unit,
    viewModel: ActivityViewModel = rememberKoinInject(), // or koinInject()
) {
    val state by viewModel.uiState.collectAsState()
    ActivityScreen(state, navigateToDetails, viewModel::updateCount)
}```

```class ActivityViewModel(
    private val activityRepository: ActivityRepository,
) : ViewModel() {

    private val _uiState = MutableStateFlow(ActivityUiState())
    val uiState = _uiState.asStateFlow()

    init {
        viewModelScope.launch {
            delay(1000)
            val count = activityRepository.getCount()
            _uiState.update { ActivityUiState(count) }
        }
   }```

**Comment by Tlaster** [comment]
If you want to use DI, you might need something like [this file](https://github.com/mori-atsushi/koject/blob/c22286b39a3e6249842d148ff0a22f1fb7d37d47/compose/koject-compose-viewmodel/src/main/kotlin/com/moriatsushi/koject/compose/viewmodel/InjectViewModel.kt#L32) in your project in order to use viewmodel with DI framework.

**Comment by JoaoPint0** [comment]
That's true, it's missing a lifecycle owner to hold the viewmodel reference

**Comment by mahramane** [comment]
@JoaoPint0 
Hi
Is your problem solved?

**Comment by JoaoPint0** [comment]
Not by a library but just started caching the viewmodel on navigation

Mohammad Mohammadi ***@***.***> escreveu em sáb., 26/08/2023
às 16:56 :
