### ISSUE TITLE
 No StateHolder provided

### ISSUE THREAD

**Issue by ronjunevaldoz** [Tlaster/PreCompose#117]
Error encountered using the state flow example.

`  java.lang.IllegalStateException: No StateHolder provided`

**Comment by Tlaster** [comment]
Please ensure you're following the [setup guide](https://github.com/Tlaster/PreCompose/blob/b9cf4129fcd061cfda56fa4aa644c05f952f9220/docs/setup.md) to setup your project.

**Comment by ronjunevaldoz** [comment]
my bad forgot to setup `PreComposeActivity`, maybe it could be added as exception message. Cheers
