### ISSUE TITLE
真的一定要升级到JDK17才能用吗？

### ISSUE THREAD

**Issue by gitzhan** [Tlaster/PreCompose#121]
大佬：
之前用的1.4.3，今天升到1.5.0一下子就运行不了了，一看原来是1.5.0版本的这个库的jvmTarget被强制指定为17了（目前项目以及团队中的JDK还是11）。
看了库的相关依赖与改动，真的有必要一定强制jvmTarget=17吗？

**Comment by Tlaster** [comment]
因为Compose 1.5有一个测试版本需要target 17，刚刚测试了一下正式版似乎不需要，我可以改回去了
