### ISSUE TITLE
Ios app running failed with PreCompose

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [Tlaster/PreCompose#125]
While trying to run the app in ios simulator i'm getting this error
```
> Task :shared:compileKotlinIosSimulatorArm64 FAILED
error: Could not find "co.touchlab:stately-common" in [/Users/macbookair/projects/Trackfit-Compose, /Users/macbookair/.konan/klib, /Users/macbookair/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.0/klib/common, /Users/macbookair/.konan/kotlin-native-prebuilt-macos-aarch64-1.9.0/klib/platform/ios_simulator_arm64]
error: Compilation finished with errors

```

how to solve this issue?

**Comment by Tlaster** [comment]
Which version of Compose and Kotlin you're using right now?

**Comment by VerushkinRoman** [comment]
I think It's not PreCompose Issue. You should check co.touchlab:stately-common library. It's outdated at this point. Try downgrade kotlin version...

**Comment by JamshedAlamQaderi** [comment]
I've fixed it. I had to remove `precompose-koin` and `precompose-viewmodel` deps

**Comment by JamshedAlamQaderi** [comment]
I think problem is in precompose viewmodel and koin integration dependencies. Because i've tried it again but still failing while trying to run it on ios. android is ok. Currently i've removed both dependencies.

**Comment by anwarpro** [comment]
precompose viewmodel and koin integration throw compile exception for ios target. I've to remove both dependencies.

**Comment by JamshedAlamQaderi** [comment]
@Tlaster any progress regarding this issue?

**Comment by Tlaster** [comment]
> @Tlaster any progress regarding this issue?

Sorry I've been busy these days (I'm moving to other country), can you check if the error still exist after upgrade your project's kotlin version to 1.9.0?

**Comment by adrict99** [comment]
I have the exact same error, updating kotlin to 1.9.0 does not solve the issue for me, only deleting precompose-koin dependency allows my app to run. I also have pure Koin dependencies like koin-compose, koin-androidx-compose, koin-android, koin-core, is that a problem?

**Comment by Tlaster** [comment]
> I have the exact same error, updating kotlin to 1.9.0 does not solve the issue for me, only deleting precompose-koin dependency allows my app to run. I also have pure Koin dependencies like koin-compose, koin-androidx-compose, koin-android, koin-core, is that a problem?

Can you check if version 1.5.2 works for you?
And BTW, which version of `koinViewModel` you're using for your project? there's a [inline version](https://github.com/Tlaster/PreCompose/blob/5996978e81a3d1569ddc5f700fa4f925824b309d/precompose-koin/src/commonMain/kotlin/moe/tlaster/precompose/koin/Koin.kt#L14) that might not work for Kotlin Native target since and you can switch to [non inline version](https://github.com/Tlaster/PreCompose/blob/5996978e81a3d1569ddc5f700fa4f925824b309d/precompose-koin/src/commonMain/kotlin/moe/tlaster/precompose/koin/Koin.kt#L34) of it and check if it works?

**Comment by adrict99** [comment]
I have checked and 1.5.2 didn't work neither, with kotlin 1.9.0 at the moment. I'm not using any koinViewModel, since my project wasn't compiling I didn't inject any viewModel yet

**Comment by Tlaster** [comment]
> I have checked and 1.5.2 didn't work neither, with kotlin 1.9.0 at the moment. I'm not using any koinViewModel, since my project wasn't compiling I didn't inject any viewModel yet, but will take that into account, thanks for the input

Can you try manually add dependency to koin and koin compose like this:
```Kotlin
        val commonMain by getting {
            dependencies {
                api("io.insert-koin:koin-core:3.5.0")
                api("io.insert-koin:koin-compose:1.1.0")
            }
       }
```
precompose-koin assume that you're already have these dependencies, so declare as compileOnly, which might cause the issue.

**Comment by adrict99** [comment]
I have modified these koin versions to the ones you suggested, and had the doubt about which ones should I mark as compileOnly, marking the pure koin ones didn't work and neither did marking precompose-koin and reverting the koin deps to implementation.

This is the error thrown in the first case:
`io.insert-koin:koin-core:3.5.0 Such dependencies are not applicable for Kotlin/Native, consider changing the dependency type to 'implementation' or 'api'.`

FYI: in (:shared) commonMain I have implementation koin-core 3.5.0, api precompose, precomposeViewModel and precomposeKoin all 1.5.2, in androidMain I have koin-androidx-compose 3.4.3 and koin-android 3.5.0 and in my :androidApp module androidMain koin-compose 1.1.0 and koin-androidx-compose 3.4.3/3.5.0. Also tried with 3.4.3  and 1.0.4 and 3.5.0 for koin-core and 1.1.0 for koinCompose with no success.

**Comment by Tlaster** [comment]
Sorry for the misleading, you can try to mark both koin-core and koin-compose in your shared commonMain as api like the code snippet above.
I'm prepare a new version which should fix the issue.

**Comment by adrict99** [comment]
Thank you for your help @Tlaster  with api it didn't work neither for me, I'll wait until the new version. Maybe it would help to describe if koin dependencies should have x versions for each version of precompose in the setup docs, looking forward to the next version

**Comment by Tlaster** [comment]
New release 1.5.3 should fix the issue, you can try it now.

**Comment by adrict99** [comment]
I appreciate your help, now it is running correctly on iOS, but it is crashing on Android with error:

`java.lang.NoSuchMethodError: No static method loadModules$default(Lorg/koin/core/Koin;Ljava/util/List;ZILjava/lang/Object;)V in class Lorg/koin/core/Koin; or its super classes (declaration of 'org.koin.core.Koin' appears in /data/app/~~/com.user.project==/base.apk!classes17.dex)` commenting precomposeKoin solves the problem.

And on iOS when I try to use the viewModel I get this same error https://github.com/Tlaster/PreCompose/issues/141, could you tell me please the appropriate way to instantiate precompose viewModel on composables? I have seen a way into the sample app and another way in the docs.

I have built the VM like:
import moe.tlaster.precompose.viewmodel.ViewModel

class RandomScreenViewModel(
    private val getRandomDataUseCase: GetRandomDataUseCase
) : ViewModel() {

And the modules are like this:
`val presentationModule = module {
    single { RandomScreenViewModel(getRandomDataUseCase = get()) }
}
val domainModule = module {
    single { GetRoutinesUseCase(repository = get()) }
}`

**Comment by Tlaster** [comment]
There's a new release 1.5.4(sorry for pushing that many releases) you can try and should works.

> java.lang.NoSuchMethodError: No static method loadModules$default(Lorg/koin/core/Koin;Ljava/util/List;ZILjava/lang/Object;)V in class Lorg/koin/core/Koin; or its super classes (declaration of 'org.koin.core.Koin' appears in /data/app/~~/com.user.project==/base.apk!classes17.dex) commenting precomposeKoin solves the problem.

As for this, you might need to check your dependencies.

**Comment by adrict99** [comment]
Thank you for your effort I appreciate it, with version 1.5.4 and updating koin dependencies to the latest available versions and now it works perfectly on both platforms.

**Comment by JamshedAlamQaderi** [comment]
Thanks @Tlaster , I'm gonna try it in my existing project.

**Comment by BehnamMaboodi** [comment]
I still encounter the `Could not find "co.touchlab:stately-common" `error with all versions (from 1.5.4 to 1.5.10).

I resolved it by manually adding `implementation("co.touchlab:stately-common:2.0.6")`.
