### ISSUE TITLE
Error Ios Build after update from 1.4.3 to 1.5.0

### ISSUE THREAD

**Issue by VerushkinRoman** [Tlaster/PreCompose#126]
Hi, can't build Ios app after updating compose to 1.5.0 and PreCompose to 1.5.0

`Could not find "/Users/posse/.gradle/caches/modules-2/files-2.1/moe.tlaster/precompose-uikitarm64/1.5.0/1c16d2958d61f91eb9480dc4fa31573bb3537a02/precompose.klib" in [/Users/posse/StudioProjects/dsrMultiplatform/iosApp/Pods, /Users/posse/.konan/klib, /Users/posse/.konan/kotlin-native-prebuilt-macos-aarch64-1.8.22/klib/common, /Users/posse/.konan/kotlin-native-prebuilt-macos-aarch64-1.8.22/klib/platform/ios_arm64]`

**Comment by VerushkinRoman** [comment]
When I update kotlin to 1.9.0, error is gone. But other libraries still not fully supporting it. I have to stay at 1.8.22 at this point, but PreCompose not working at iOS build ((

**Comment by Tlaster** [comment]
I will downgrade the kotlin version of precompose and check if it works.

**Comment by luangs7** [comment]
same here

**Comment by luangs7** [comment]
any updates about this error?

**Comment by Tlaster** [comment]
> any updates about this error?

You can upgrade your kotlin version to 1.9.0 for now.

**Comment by Tlaster** [comment]
Close as inactive, reopen if you still have the same issue.
