### ISSUE TITLE
how to use navigateForResult

### ISSUE THREAD

**Issue by mahramane** [Tlaster/PreCompose#127]
how to use navigateForResult?
i didn't find document about it.
please give me an example.

**Comment by Tlaster** [comment]
You can use navigateForResult with [goBackWith](https://github.com/Tlaster/PreCompose/blob/fe01324fca107992e2c5e7f1c4f81d9b61fbd9ba/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt#L93) in onter route that you want to return result.

**Comment by Tlaster** [comment]
close as inactive
