### ISSUE TITLE
PreComposeApplication not respecting safe area in iOS

### ISSUE THREAD

**Issue by ABHI165** [Tlaster/PreCompose#132]
I have used compose multi-platform for sharing ui between android and iOS in my KMM library. I am using Precompose for handling navigation. The problem is that whenever I push  my module's viewController which is a `PreComposeApplication` , it does not respect the device safe area in iOS.
![Screenshot 2023-09-06 at 4 59 42 PM](https://github.com/Tlaster/PreCompose/assets/56068132/e52c34b1-ac43-4e08-84a1-85812ff6d00a)

**Comment by adrict99** [comment]
You can use a library from the creator of PreCompose called SafeArea: https://github.com/Tlaster/SafeArea or learn from its source code for what you need.

**Comment by Tlaster** [comment]
PreCompose does not handle any WindowInsets (and should not), you can do it your self.

**Comment by Tlaster** [comment]
close as inactive
