### ISSUE TITLE
[Desktop] No StateHolder provided

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [Tlaster/PreCompose#133]
Hi I am getting the "No StateHolder provided" error while running the basic app. Below are my configuration

**build.gradle.kts**:
```
api("moe.tlaster:precompose:1.5.1")
api("moe.tlaster:precompose-viewmodel:1.5.1")
api(compose.foundation)
api(compose.animation)
```

**Main.kt:**
```
fun main() = application {
     val preComposeNav = rememberNavigator()

    PreComposeWindow(
        title = "PreCompose Sample",
        onCloseRequest = {
            exitApplication()
        },
    ) {
        PreComposeNavigator(preComposeNav)
    }
 }
```

**Router.kt:** 

```
@Composable
fun PreComposeNavigator(navigator: Navigator) {

    NavHost(navigator = navigator, initialRoute = "/home") {
        scene("/home") {

            Scaffold {
                Column {
                    Button(onClick = { navigator.navigate("/dashboard") }) {
                        Text("Next")
                    }
                }
            }
        }
        scene("/dashboard") {

            Scaffold {
                Column {
                    Button(onClick = { navigator.popBackStack() }) {
                        Text("Next")
                    }
                }
            }
        }
    }
}
```

**Error:**

```
Exception in thread "main" java.lang.IllegalStateException: No StateHolder provided
	at moe.tlaster.precompose.stateholder.StateHolderKt$LocalStateHolder$1.invoke(StateHolder.kt:45)
	at moe.tlaster.precompose.stateholder.StateHolderKt$LocalStateHolder$1.invoke(StateHolder.kt:44)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.compose.runtime.LazyValueHolder.getCurrent(ValueHolders.kt:29)
	at androidx.compose.runtime.LazyValueHolder.getValue(ValueHolders.kt:31)
	at androidx.compose.runtime.CompositionLocalMapKt.read(CompositionLocalMap.kt:88)
	at androidx.compose.runtime.ComposerImpl.consume(Composer.kt:2050)
	at moe.tlaster.precompose.navigation.NavigatorKt.rememberNavigator(Navigator.kt:118)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:86)
	at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:85)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:115)
	at androidx.compose.ui.window.Application_desktopKt$application$1$1.invoke(Application.desktop.kt:114)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:226)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1$1.invoke(Application.desktop.kt:225)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:221)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2$1.invoke(Application.desktop.kt:219)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:39)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3341)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3274)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1013)
```

Am I missing anything here?

**Comment by adrict99** [comment]
Also happening on 1.4.3 version, the error is related with the creation of "val preComposeNav = rememberNavigator()" in my case, still didn't found a solution yet.

**Comment by Lavmee** [comment]
It seems to me that you need to call the "rememberNavigator" function inside the PreComposeWindow block.

**Comment by adrict99** [comment]
> 

That has worked perfectly fine for me! Following this based on your answer: https://github.com/Tlaster/PreCompose/blob/master/docs/setup.md

Thanks!

**Comment by adrict99** [comment]
> It seems to me that you need to call the "rememberNavigator" function inside the PreComposeWindow block.

That has worked perfectly fine for me! Following this based on your answer: https://github.com/Tlaster/PreCompose/blob/master/docs/setup.md

Thanks!

**Comment by Tlaster** [comment]
> It seems to me that you need to call the "rememberNavigator" function inside the PreComposeWindow block.

Seems like the doc needs an update and include it.

**Comment by hatteajay1212** [comment]
Hi , i am getting the same issue for android.

@Composable
fun RootView(){
    val navigator = rememberNavigator()

    NavHost(
        navigator = navigator,
        initialRoute = "/home"
    ){
        scene(
            route = "/home"
        ){
            val client = "NAFED"
            ComposeMultiplatformAppTheme {
                Scaffold(
                   content = {
                       Column(
                           modifier = Modifier.padding(it),
                           verticalArrangement = Arrangement.Center
                       ) {
                           Text(
                               "Home Screen"
                           )
                       }
                   }
                )
                FloatingActionButton(
                    onClick = {
                        navigator.navigate("/auctionFloor/$client")
                    }
                ){
                    Icon(
                        Icons.Filled.Home,
                        contentDescription = null
                    )
                }
            }
        }

        scene(
            route = "/auctionFloor/{client}"
        ){backStackEntry ->
            val client = backStackEntry.path<String>("client")

            if (null != client){
                ComposeMultiplatformAppTheme {
                    Scaffold(
                        topBar = {
                            TopAppBar(
                                title = {
                                    Text(
                                        "Auction Floor"
                                    )
                                },
                                navigationIcon = {
                                    IconButton(
                                        onClick = {
                                            navigator.popBackStack()
                                        }
                                    ) {
                                        Icon(
                                            Icons.Filled.ArrowBack,
                                            contentDescription = null
                                        )
                                    }
                                }
                            )
                        },
                        content = {
                            Column(
                                modifier = Modifier.padding(it),
                                verticalArrangement = Arrangement.Center
                            ) {
                                Text(
                                    "Auction Floor Screen $client"
                                )
                            }
                        }
                    )

                    FloatingActionButton(
                        onClick = {
                            navigator.navigate("/details/1235676")
                        }
                    ) {
                        Icon(
                            Icons.Filled.AccountBox,
                            contentDescription = null
                        )
                    }
                }
            }else{
                println("client is Null")
            }
        }

        scene(
            route = "/details/{tokenId}"
        ){backStackEntry ->
            val tokenId = backStackEntry.path<Long>("tokenId")
            ComposeMultiplatformAppTheme {
                Scaffold(
                    topBar = {
                        TopAppBar(
                            title = {
                                Text(
                                    "Auction Details"
                                )
                            },
                            navigationIcon = {
                                IconButton(
                                    onClick = {
                                        navigator.popBackStack()
                                    }
                                ){
                                    Icon(
                                        Icons.Filled.ArrowBack,
                                        contentDescription = null
                                    )
                                }
                            }
                        )
                    },
                    content = {
                        Column(
                            modifier = Modifier.padding(it),
                            verticalArrangement = Arrangement.Center
                        ) {
                            Text(
                                "Auction Details $tokenId"
                            )
                        }
                    }
                )
            }
        }
    }
}

@Tlaster Any solution for this

**Comment by hatteajay1212** [comment]
Yes , i have used PreComposeActivity for android.

class MainActivity : PreComposeActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContent {
            RootView()
        }
    }
}

**Comment by Tlaster** [comment]
> @Tlaster Yes , i have used PreComposeActivity for android.
> 
> class MainActivity : PreComposeActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState) setContent { RootView() } } }

And can you check if you're using `moe.tlaster.precompose.lifecycle.setContent` instead of jetpack's version of `setContent`?

**Comment by hatteajay1212** [comment]
@Tlaster Sry, i was using jetpack's setContent instead of moe.tlaster.precompose.lifecycle.setContent.It is working fine now for android.Thanks for the help.

**Comment by Tlaster** [comment]
close as resolve.
