### ISSUE TITLE
[Android] Scene with backStackEntry called multiple times

### ISSUE THREAD

**Issue by ronjunevaldoz** [Tlaster/PreCompose#134]
I suspect that  the scene with back stack entry is being loop by the total number of scenes?
 
```kotlin
scene(route = "/screens/home") {
}
scene(route = "/screens/settings") {
}
scene(route = "/screens/menu") {
}
scene(route = "/${Routes.ADD_EDIT_TASK}/{taskId}") { backStackEntry -> 
   println("scene called")
   // only experience the issue when below line is included
   backStackEntry.path<String>("taskId")?.let { taskId ->
      // empty implementation
   }
}
```
Output with ` backStackEntry.path<String>("taskId")?.let { taskId ->`
```kotlin
scene called
scene called
scene called
scene called
```
Output without ` backStackEntry.path<String>("taskId")?.let { taskId ->`
```kotlin
scene called
```

**Comment by Tlaster** [comment]
As I understand it, it's normal for a composable function to be called many times (I usually assume the composable function is called 10000 times). So if the call doesn't have a performance impact, I think it's ok overall.
And the back stack entry is [constructed only when navigating to the new scene](https://github.com/Tlaster/PreCompose/blob/0c3a662c93a67eafff9260f882c6bb0bd0239365/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt#L113C51-L113C66), and precompose does not loop the back stack entry.

**Comment by tiper** [comment]
Hey @ronjunevaldoz the issue seems to occur because `BackStackEntry` is seem as unstable, so when a scene interacts with it will cause a recomposition.

@Tlaster I've opened a PR #162 that tries to mitigate the issue in the least intrusive way possible.

**Comment by Tlaster** [comment]
Close as fixed.
