### ISSUE TITLE
Question: How do I disable backpress on specific screen?

### ISSUE THREAD

**Issue by ronjunevaldoz** [Tlaster/PreCompose#135]
I'm not sure how do I disable back press using the library. I've seen the `BackHandler` but not sure how do I used it here. Tried to use `PopUpTo`.

```kotlin
navigator.navigate(
     it.route,
    NavOptions(  popUpTo = PopUpTo(it.route, true))
)
```

**Comment by Tlaster** [comment]
`BackHandler` is the same as the Jetpack's `BackHandler`, you can check out the [doc](https://developer.android.com/jetpack/compose/libraries#handling_the_system_back_button) from jetpack

**Comment by Tlaster** [comment]
Close as inactive.
