### ISSUE TITLE
iOS App Build Failure with Precompose ViewModel Library

### ISSUE THREAD

**Issue by msomu** [Tlaster/PreCompose#141]
I encountered an issue while trying to build the iOS app with the Precompose ViewModel library 1.5.1. The error message I received is as follows:

```w: Cannot infer a bundle ID from packages of source files and exported dependencies, use the bundle name instead: shared. Please specify the bundle ID explicitly using the -Xbinary=bundleId=<id> compiler flag.
e: Compilation failed: Generation of stubs for class org.jetbrains.kotlin.ir.symbols.impl.IrTypeParameterPublicSymbolImpl is not supported yet

 * Source files: 
 * Compiler version: 1.9.0
 * Output kind: FRAMEWORK
```

This error is preventing me from proceeding with the build. I'm seeking guidance on any possible workarounds or solutions to resolve this issue and successfully build the iOS app. FYI, the android app runs well and there are no issues with the android app.

The kotlin version was first `1.9.10` and i changed it to `1.9.0` still the issue is present.

**Comment by Tlaster** [comment]
Are you using inline version of [viewModel](https://github.com/Tlaster/PreCompose/blob/2672858910bb3521e33c0efe2c1f06984258f38b/precompose-viewmodel/src/commonMain/kotlin/moe/tlaster/precompose/viewmodel/ViewModelAdapter.kt#L19) in composable function? If so can you try non inline version of `viewModel` and see if it works?

**Comment by Tlaster** [comment]
Close as inactive, reopen if you still have the same issue.
