### ISSUE TITLE
Clear whole backstack

### ISSUE THREAD

**Issue by sawil314** [Tlaster/PreCompose#142]
Hi,
is it possible to clear the whole backstack?
For example after Logout.
If I understand it corrctly in Jetpack Navigation it is possible to access the navGraph which is always the first BackstackEntry and Pop up to it.
Is something similar possible in Precompose Navigation?

**Comment by Tlaster** [comment]
You can use [PopUpTo](https://github.com/Tlaster/PreCompose/blob/master/docs/component/navigation.md#navoptions) with `inclusive = true` when navigating to new route.

**Comment by Tlaster** [comment]
Seems like a new use case I've never think of, I'll add a way to clear back stacks in navigator.

**Comment by sawil314** [comment]
Thank you!

**Comment by priyanshuhere** [comment]
@sawil314 You can try using PopUpTo.First(inclusive = true) when navigating to the new route. This would remove all screens from the stack barring the new navigation destination.

**Comment by sawil314** [comment]
@priyanshuhere Thank you, that was the function I was looking for!
