### ISSUE TITLE
Can I use precompose with insetsx together?

### ISSUE THREAD

**Issue by NakiriYuuzu** [Tlaster/PreCompose#156]
Because precompose and insetsx has own controller, but I tried many pattern, iOS part always is white screen.

**Comment by Tlaster** [comment]
You can wrap you Content like this:
```Kotlin
        val holder = remember {
            PreComposeWindowHolder()
        }
        ProvidePreComposeCompositionLocals(
            holder,
        ) {
            App()
        }
```
What `PreComposeApplication` does is just wrap the content with some composition local that precompose needs.

**Comment by NakiriYuuzu** [comment]
thank you so much
