### ISSUE TITLE
No StateHolder provided

### ISSUE THREAD

**Issue by muneeb36** [Tlaster/PreCompose#157]
how to fix this --> llegalStateException: No StateHolder provided on rememberNavigator()

**Comment by Tlaster** [comment]
Can you check if your project is following the [setup guide](https://github.com/Tlaster/PreCompose/blob/b9cf4129fcd061cfda56fa4aa644c05f952f9220/docs/setup.md)?

**Comment by muneeb36** [comment]
i have tried all of these can you please check what is the issue i really
appreciate your help
my project link is this i'm just trying to navigate between screens

https://github.com/muneeb36/Compose_Multiplatfor_KMP

**Comment by Tlaster** [comment]
Please do read the [setup guide](https://github.com/Tlaster/PreCompose/blob/b9cf4129fcd061cfda56fa4aa644c05f952f9220/docs/setup.md), not only you need to add dependencies but also you need to change the code [here](https://github.com/muneeb36/Compose_Multiplatfor_KMP/blob/7079cd356f2e88aa68814d97f80895f7768f3a74/androidApp/src/main/java/com/example/mykmp_app/android/MainActivity.kt#L15), [here](https://github.com/muneeb36/Compose_Multiplatfor_KMP/blob/7079cd356f2e88aa68814d97f80895f7768f3a74/androidApp/src/main/java/com/example/mykmp_app/android/MainActivity.kt#L17C13-L17C13) and [here](https://github.com/muneeb36/Compose_Multiplatfor_KMP/blob/7079cd356f2e88aa68814d97f80895f7768f3a74/shared/src/iosMain/kotlin/com/example/mykmp_app/App_ios.kt#L5).

**Comment by muneeb36** [comment]
Thanks @Tlaster
Issue Fixed

**Comment by Tlaster** [comment]
Close as fixed.
