### ISSUE TITLE
How to support iosSimulatorArm64？

### ISSUE THREAD

**Issue by GavinNovate** [Tlaster/PreCompose#17]
My build.gradle.kts

``` kotlin
plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    id("org.jetbrains.compose")
}

kotlin {
    android()
    iosX64("uikitX64")
    iosArm64("uikitArm64")
    iosSimulatorArm64("uikitSimArm64")

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(compose.ui)
                implementation(compose.foundation)
                implementation(compose.material)
                implementation(compose.runtime)
                implementation(libs.precompose)
            }
        }
    }
}
```

Build logs
```
A problem occurred configuring project ':demo'.
> Could not resolve all dependencies for configuration ':demo:uikitSimArm64CompileKlibraries'.
```

**Comment by Tlaster** [comment]
PreCompose does not support iosSimulatorArm64 yet, will add in next release

**Comment by Tiebe** [comment]
@Tlaster Is there a new release yet?

**Comment by Tlaster** [comment]
> @Tlaster Is there a new release yet?

Not yet, adding iosSimulatorArm64 will cause a build error and I'm still figuring out the reason, and recently I was busy so the issue is being delayed.

**Comment by Tiebe** [comment]
> > @Tlaster Is there a new release yet?
> 
> Not yet, adding iosSimulatorArm64 will cause a build error and I'm still figuring out the reason, and recently I was busy so the issue is being delayed.

Alright, take your time!

**Comment by Tlaster** [comment]
Done in [1.3.14](https://github.com/Tlaster/PreCompose/releases/tag/1.3.14)
