### ISSUE TITLE
precompose-viewmodel does not depend on precompose

### ISSUE THREAD

**Issue by zsmb13** [Tlaster/PreCompose#181]
The `moe.tlaster:precompose-viewmodel` library doesn't depend on `moe.tlaster:precompose`, so classes/declarations from the base library are missing if you only add the viewmodel dependency and compilation fails.

The add-on libraries (viewmodel, molecule, koin) should depend on the base library in their published POM files so that the base library is automatically included.

**Comment by Tlaster** [comment]
Yes, sub module should declare dependency to its parent module, so we can just add one dependency an everything will just work, I'll fix this later.
