### ISSUE TITLE
Navigate back with result

### ISSUE THREAD

**Issue by darkmat13r** [Tlaster/PreCompose#186]
How to get the result passed in 
`navigator.goBackWith(result)`?

**Comment by Tlaster** [comment]
You can use `navigator.navigateForResult`

**Comment by darkmat13r** [comment]
In that case I have to know what route I want to go. Is there any other options to pass the result on back screen.

**Comment by Tlaster** [comment]
No, `navigator.goBackWith` just navigate up and pass the result to the previous screen, this should fit the use case like a picker, for example: in screen A, you want to select something in screen B, you can use `navigator.navigateForResult` in screen A, and when user select something in screen B, you can use `navigator.goBackWith` in screen B, it will pass the result to screen A and close the screen B.

**Comment by darkmat13r** [comment]
Thanks :)

**Comment by 1006245347** [comment]
How to the value ,ScreenA ->navigator.navigateForResult(B),SceenB ->navigator.goBackWith("data"),In ScreenA how to get "data"?
