### ISSUE TITLE
compose desktop 当点击关闭窗口时，NavHost中的内容变成了空白

### ISSUE THREAD

**Issue by Matcha-xiaobin** [Tlaster/PreCompose#187]
fun main() = application {
    var exitDialog by remember { mutableStateOf(false) }
    Window(
        onCloseRequest = {
            exitDialog = true
        }
    ) {
        AppTheme {
            PreComposeApp {
                App(window)
                if (exitDialog) {
                    showTextDialog(
                        content = "Are you sure?"
                    ) {
                        if (it) {
                            exitApplication()
                        }
                        exitDialog = false
                    }
                }
            }
        }
    }
}

NavHost相关：
val navigator = rememberNavigator()
NavHost(
                navigator = navigator,
                initialRoute = "home"
            ) {
                scene("home") { 
                      ... 
                }
           }

当我点击关闭窗口时，会弹出弹窗询问是否确定关闭，但此时，NavHost中的内容已经变成了空白。

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/Tlaster/PreCompose/assets/5775066/47cf866d-1bd4-4f61-b27c-07e66d1c61c3)
当我点击关闭时，触发了这个，导致清空了backStacks中的内容

**Comment by Matcha-xiaobin** [comment]
![image](https://github.com/Tlaster/PreCompose/assets/5775066/56c00060-2f9e-42e6-98e6-81a0ea969381)
若使用windowClosed，而不是windowClosing，是否可以解决这个问题？
![image](https://github.com/Tlaster/PreCompose/assets/5775066/8170f1cc-0898-46de-b1ff-ee6a2dd587e7)

**Comment by Tlaster** [comment]
是的，我已经在 #188 进行修复

**Comment by Matcha-xiaobin** [comment]
顺带的，我想提一个建议，我想通过navigator 轻松的获取当前在哪个位置

**Comment by Tlaster** [comment]
> 顺带的，我想提一个建议，我想通过navigator 轻松的获取当前在哪个位置

`navigator.currentEntry` 应该能够满足你的需求

**Comment by Matcha-xiaobin** [comment]
哦，好的，确实可以，是我没注意到这个
