### ISSUE TITLE
How can i use navigation like vue router?

### ISSUE THREAD

**Issue by yangwulang** [Tlaster/PreCompose#20]
As the title says. I have two top level screen, and multiple sub screen under one screen.

such like this graph

```
            one                                  two
      /       |       \                    /      |        \
     one     two    three                one     two      three

```
How can i achieve it?

**Comment by Tlaster** [comment]
You can define two `NavHost` in the same level like this:
```
@Composable
fun TopLevel() {
    val navigatorOne = rememberNavigator()
    val navigatorTwo = rememberNavigator()
    NavHost(
        navigator = navigatorOne,
        //...
    ) {
        //...
    }
    NavHost(
        navigator = navigatorTwo,
        //...
    ) {
        //...
    }
}
```

**Comment by yangwulang** [comment]
> You can define two `NavHost` in the same level like this:
> 
> ```
> @Composable
> fun TopLevel() {
>     val navigatorOne = rememberNavigator()
>     val navigatorTwo = rememberNavigator()
>     NavHost(
>         navigator = navigatorOne,
>         //...
>     ) {
>         //...
>     }
>     NavHost(
>         navigator = navigatorTwo,
>         //...
>     ) {
>         //...
>     }
> }
> ```

OK, thank you for your answer. Can I use it like this?

```
@Composable
fun TopLevel() {
    val navigator = rememberNavigator()
    NavHost(
        navigator = navigator
    ) {
        scene("/one") {
           NavHost(
              navigator = navigator,
           ) {
             //...
           }
        }
    }
    
}
```

I see from the RouteBuilder class that the scene function carries the deepLinks parameter. What is the function of this parameter?

**Comment by Tlaster** [comment]
the deeplinks only works if you call `navigator.navigate`, otherwise it does nothing.

**Comment by Tlaster** [comment]
close as inactive.

**Comment by andremion** [comment]
> You can define two `NavHost` in the same level like this:
> ```
> @Composable
> fun TopLevel() {
>     val navigatorOne = rememberNavigator()
>     val navigatorTwo = rememberNavigator()
>     NavHost(
>         navigator = navigatorOne,
>         //...
>     ) {
>         //...
>     }
>     NavHost(
>         navigator = navigatorTwo,
>         //...
>     ) {
>         //...
>     }
> }
> ```

@Tlaster , calling `rememberNavigator()` always returns the same navigator instance. So both `navigatorOne` and `navigatorTwo` will be the same.
I had an issue when used two NavHosts because of the same instance.

I can create a small PR to include an optional `name` parameter to the `rememberNavigator` function to be used as a key for fetching navigators from the `StateHolder`.

What do you think?

**Comment by Tlaster** [comment]
> > You can define two `NavHost` in the same level like this:
> > ```
> > @Composable
> > fun TopLevel() {
> >     val navigatorOne = rememberNavigator()
> >     val navigatorTwo = rememberNavigator()
> >     NavHost(
> >         navigator = navigatorOne,
> >         //...
> >     ) {
> >         //...
> >     }
> >     NavHost(
> >         navigator = navigatorTwo,
> >         //...
> >     ) {
> >         //...
> >     }
> > }
> > ```
> 
> @Tlaster , calling `rememberNavigator()` always returns the same navigator instance. So both `navigatorOne` and `navigatorTwo` will be the same. I had an issue when used two NavHosts because of the same instance.
> 
> I can create a small PR to include an optional `name` parameter to the `rememberNavigator` function to be used as a key for fetching navigators from the `StateHolder`.
> 
> What do you think?

Yes a `name` parameter would be nice!
