### ISSUE TITLE
navigator.currentEntry.collectAsStateWithLifecycle always returns null on iOS

### ISSUE THREAD

**Issue by FunkyMuse** [Tlaster/PreCompose#202]
`val currentEntry by navigator.currentEntry.collectAsStateWithLifecycle(null)`

if it's replaced with

`val currentEntry by navigator.currentEntry.collectAsState(null)` then it works, probably the `LifecycleOwner` doesn't work properly on iOS or it's not yet implemented?

**Comment by FunkyMuse** [comment]
I ran this sample btw https://github.com/Lavmee/precompose-navigation-typesafe/tree/main/sample

**Comment by FunkyMuse** [comment]
Seems like a quick fix, thanks.

**Comment by FunkyMuse** [comment]
@Tlaster can we get a release with this?

**Comment by Tlaster** [comment]
> @Tlaster can we get a release with this?

Yes, I'm about to release a new version.
