### ISSUE TITLE
Kotlin 1.8

### ISSUE THREAD

**Issue by chipnesh** [Tlaster/PreCompose#21]
Hello.
Any chance this library will be migrated to kotlin 1.8?

**Comment by Tlaster** [comment]
I'm waiting for compose-jb to release version 1.3.0, which is [just around the corner](https://github.com/JetBrains/compose-jb/pull/2627).

**Comment by Tlaster** [comment]
Done in [1.3.14](https://github.com/Tlaster/PreCompose/releases/tag/1.3.14)
