### ISSUE TITLE
iOS crash during backward swipe

### ISSUE THREAD

**Issue by KostadinAlmishev** [Tlaster/PreCompose#210]
Steps to reproduce:

- Add SwipeProperties in NavHost
- Click on a button to navigate to next screen
- During animation, swipe backward
- App crashes

Same happens if click on multiple navigation buttons (multitouch) at same time.

Stacktrace:
[errlog.txt](https://github.com/Tlaster/PreCompose/files/13629439/errlog.txt)

PS: /secured/settings is route in previous screen.

**Comment by Tlaster** [comment]
Seems like the dirty workaround [here](https://github.com/Tlaster/PreCompose/blob/51f658cb6ccb9e45970d7cab073869d5be35c322/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackEntry.kt#L22) not working as expected, I'm working on a fix.

**Comment by KostadinAlmishev** [comment]
Can you create new release with fix?

**Comment by Tlaster** [comment]
Yes, I'm about to release a new version after I implement a small functionality: supporting go back with options.

**Comment by KostadinAlmishev** [comment]
@Tlaster I updated to v1.5.9, cleaned build files, deleted app from my iPhone and installed it again, but I am still getting the same error..

[err.txt](https://github.com/Tlaster/PreCompose/files/13689711/err.txt)

**Comment by Tlaster** [comment]
Seems like a wrong fix for it, I'm working on a new fix.

**Comment by Tlaster** [comment]
Can you try version 1.5.10 which should fix the issue?
