### ISSUE TITLE
Popback Stack with popUpTo

### ISSUE THREAD

**Issue by mikedawson** [Tlaster/PreCompose#214]
Hello,

I really, really like this library! I'm adapting our Jetpack Compose app to run on Android and Desktop, and this gave me the functionality needed on the desktop without a whole new learning curve and philosophy.

The one thing I'm missing is popBackStack with arguments to specify where to pop up to e.g. as per the [Jetpack Navigation popBackStack](https://developer.android.com/reference/androidx/navigation/NavController#popBackStack(kotlin.String,kotlin.Boolean,kotlin.Boolean)). 

In the meantime, I was able to workaround this by using an effect that keeps going back until it hits the intended target.

I looked at the code, it seems like the functionality that handles this for navigate could also be used for pop. Is this something that is in the works? Something where you would want a pull request?

Thanks again,

-Mike

**Comment by Tlaster** [comment]
Go back with pop up option was just added in [recent release](https://github.com/Tlaster/PreCompose/releases/tag/1.5.9), but not documented yet and you can check the [navigator's code](https://github.com/Tlaster/PreCompose/blob/6abfc0b4b6215309c90398876cb750f59b23218a/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt#L114)

**Comment by mikedawson** [comment]
Thank you @Tlaster ! Will update and then I can remove the workaround.
