### ISSUE TITLE
is it possible to get launchSingleTop based on path parameter

### ISSUE THREAD

**Issue by sphrak** [Tlaster/PreCompose#22]
hello,
is it possible to get `launchSingleTop = true` behavior on scene destinations that have different path parameters?

For example I have a list of detail views, and when clicked i want only 1 such instance to exist given the path parameter is the same.

```
nav to /home/1 (1 instance)
nav to /home/2 (1 instance)
nav to /home/2 (same instance as above)
```

Currently in 1.3.14 it seems that `launchSingleTop=true`, will only ever create 1 instance of a scene regardsless of its path parameters.

Kindly

**Comment by Tlaster** [comment]
It should be possible, but I don't think it's good practice, you can load your data from the data source depending on the parameters you get from the route, you can use [this](https://developer.android.com/topic/architecture) as a guideline.

**Comment by sphrak** [comment]
@Tlaster sorry I probably explained it backwards, i am loading the data once I enter a screen already - 

the scenario i am trying to prevent is if I am on "Route A", and a navigation event leads to "Route A" again, then that screen will be reloaded even tho I am already on that route and i want to prevent that

**Comment by Tlaster** [comment]
Sorry for the late reply, it's been a busy week for me.
Yeah, that makes sense, I'll get it working later.

**Comment by sphrak** [comment]
@Tlaster no worries, rest is more important. 

I actually got this working here -- https://github.com/Tlaster/PreCompose/pull/24

The tests pass, but I am not sure if this might be too naive of a solution :-)
