### ISSUE TITLE
Sample ToDo app crashes with KoinCompose 1.1.2

### ISSUE THREAD

**Issue by Woren** [Tlaster/PreCompose#222]
After updating KoinCompose from 1.1.0 to 1.1.2 (io.insert-koin:koin-compose) in sample ToDo app crashes after configuration change (e.i. orientation change) on Android. 

The reason is that Koin added check if Koin Application already exists inside KoinApplication composable.

**Comment by Tlaster** [comment]
Seems like the behavior changed, I'll update the sample later.
