### ISSUE TITLE
invoking goBack will break navigation if nav transitions are used

### ISSUE THREAD

**Issue by sphrak** [Tlaster/PreCompose#226]
Hello, 
This seems to have been introduced between somewhere [1.5.8..1.5.9](https://github.com/Tlaster/PreCompose/compare/1.5.8...1.5.9) - what happens when the bug occurs is that `canGoBack` always returns `false` [here](https://github.com/Tlaster/PreCompose/blob/master/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/BackStackManager.kt#L99)

Made a repro here:  https://github.com/sphrak/precompose-gobackbug

Steps:
1. click some destinations
2. click "back button"
3. click some destinations again
4. ???
5. can no longer navigate

AFAIK the bug only happens if you have `navTransitions` specified ie https://github.com/sphrak/precompose-gobackbug/blob/main/src/main/kotlin/Main.kt#L96

I will investigate more tomorrow.

**Comment by Tlaster** [comment]
Nice catch! I'm being busy recent week so might not have time to figure it out recentlly.

**Comment by sphrak** [comment]
@Tlaster no worries, I have done some more investigation and while I still don't understand completely why it happens it seems to have to do with specifying `ExitTransition.None`/`EnterTransition.None`.. If I use `fadeIn`, `fadeOut` or simply dont specify any (effectively using the default [NavTransition](https://github.com/Tlaster/PreCompose/blob/master/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/transition/NavTransition.kt#L53)) instead then the bug goes away.

**Comment by Tlaster** [comment]
I think I've figure it out, it because [here](https://github.com/Tlaster/PreCompose/blob/ac3428a2e03feb5702a0fcb77ea70152f5fe10c2/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt#L145) is not being trigger when `transition.isRunning` is `false` quickly, change it to `SideEffect` can resolve the issue.
