### ISSUE TITLE
Please add support for named route

### ISSUE THREAD

**Issue by sadiqueWiseboxs** [Tlaster/PreCompose#232]

**Comment by Tlaster** [comment]
Can you explain more about what is a named route?

**Comment by sadiqueWiseboxs** [comment]
A named route is as same as path route 
in path route we give path like `/login` or `/home` and for named route we also give a unique name to the route like for `/login` we name it `login` this will seem unnecessary for single route but it is very usable for nested route [https://router.vuejs.org/guide/essentials/nested-routes.html](https://router.vuejs.org/guide/essentials/nested-routes.html) look at this one it very useful

**Comment by Tlaster** [comment]
Sorry but I don't get it, PreCompose does support `login` (without the slash at the beginning) as a route, is there anything I missing?
