### ISSUE TITLE
Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8

### ISSUE THREAD

**Issue by Him188** [Tlaster/PreCompose#236]
![image](https://github.com/Tlaster/PreCompose/assets/12100985/39d05dc1-35a1-405b-9ae1-57f9bbc57a8f)

My Gradle configuration:
```kotlin
kotlin {
    androidTarget()
    jvm("desktop") {
        jvmToolchain(17)
    }
```
Although I don't know why my Kotlin is still targeting 1.8 (maybe due to the android target?), I think we should compile the library against 1.8 so that we support all Kotlin targets.

**Comment by Tlaster** [comment]
Seems like the same as #158 , can you please check if manually set kotlin's jvm target for all project like [this](https://github.com/Tlaster/PreCompose/blob/c555d98f09768536206393f845162b5d3fe8d285/build.gradle.kts#L11) works for you?

**Comment by Him188** [comment]
The workaround does not fix my problem. I can't use `koinViewModel` in commonMain, but can in both jvmMain and androidMain. Looks like the Kotlin plugin is to blame.

What JDK11-exclusive features does PreCompose depend on? I would like to do a composite build with jvm target 8.

**Comment by Him188** [comment]
It looks like KTIJ's bug as per https://youtrack.jetbrains.com/issue/KTIJ-18375/MPP-IDE-common-source-set-always-has-default-JVM-target#focus=Comments-27-8204064.0-0

The issue has been fixed in 233 however, the latest Android Studio is 232.

**Comment by Him188** [comment]
Upgrading to AS 233 Canary 3 solved this issue.
