### ISSUE TITLE
back button doesn't close floating scene

### ISSUE THREAD

**Issue by FunkyMuse** [Tlaster/PreCompose#249]
clicking back button or swiping back on Android doesn't close the floating scene when using androidx.compose.material3.ModalBottomSheet

haven't tested on iOS

**Comment by Tlaster** [comment]
Not sure what `androidx.compose.material3.ModalBottomSheet` have done internally, I'm looking into it.

**Comment by FunkyMuse** [comment]
if i only knew how to trigger back swipe on iOS i would've done it

on Android, pressing also the back button doesn't work, nor swiping back using gesture navigation
