### ISSUE TITLE
Add previousEntry alongside currentEntry to Navigator

### ISSUE THREAD

**Issue by tomczyn** [Tlaster/PreCompose#253]
Would it be possible to add a `previousEntry` to `Navigator` alongside `currentEntry`?
We could then easily achieve sending data to the previous screen through the `SavedStateHolder`. Here's an example use case based on StackOverflow question: https://stackoverflow.com/a/70631089/6690664

**Comment by Tlaster** [comment]
If you just want to passing objects as a result between scene, you can just use [`navigateForResult`](https://github.com/Tlaster/PreCompose/blob/40e26ce02ebbe700a8ce59c651b84f58f0dbbb9e/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt#L83) with [`goBackWith`](https://github.com/Tlaster/PreCompose/blob/40e26ce02ebbe700a8ce59c651b84f58f0dbbb9e/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/Navigator.kt#L105).

**Comment by Tlaster** [comment]
A workaround to sending multiple values without `previousEntry` is to wrap all the values as a class, and both `navigateForResult` and `goBackWith` are optional so you can pass something or nothing.
A `previousEntry` would be nice to have, [precompose already using it internally](https://github.com/Tlaster/PreCompose/blob/40e26ce02ebbe700a8ce59c651b84f58f0dbbb9e/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/NavHost.kt#L137) so why not.
