### ISSUE TITLE
BackStackEntry extension "path" throws an exception.

### ISSUE THREAD

**Issue by john17727** [Tlaster/PreCompose#261]
Using the path extension function throws: Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option.

<img width="1728" alt="Screenshot 2024-02-04 at 4 09 04 PM" src="https://github.com/Tlaster/PreCompose/assets/35967497/cc5ff484-f3c0-4f09-8747-acdd8fd18fbe">

**Comment by Tlaster** [comment]
Which jvm target you're using? PreCompose requires jvm target 11 in order to works

**Comment by john17727** [comment]
> Which jvm target you're using? PreCompose requires jvm target 11 in order to works

Ah that makes a lot of sense. Would be great if we could be notified of that somewhere in the readme, unless I missed it. Nontheless, thanks!
