### ISSUE TITLE
Multiple back stacks NavigationBar

### ISSUE THREAD

**Issue by mahramane** [Tlaster/PreCompose#264]
Hi
Please give me an example for `NavigationBar` with 4 tabs.
I want to create a multiple back stacks Navigation Bar and save current page and tabs page data when switch between those.
also when switch between tabs `onResume` event called. 👇

```
@Composable
fun OnResume(onResume: () -> Unit) {
    OnLifecycleEvent { event ->
        if (event == Lifecycle.State.Active) onResume()
    }
}

@Composable
fun OnLifecycleEvent(onEvent: (event: Lifecycle.State) -> Unit) {
    val eventHandler = rememberUpdatedState(onEvent)
    val lifecycleOwner = rememberUpdatedState(LocalLifecycleOwner.current)

    DisposableEffect(lifecycleOwner.value) {
        val lifecycle = lifecycleOwner.value.lifecycle

        val observer = object : LifecycleObserver {

            override fun onStateChanged(state: Lifecycle.State) {
                eventHandler.value(state)
            }
        }
        lifecycle.addObserver(observer)
        onDispose {
            lifecycle.removeObserver(observer)
        }
    }
}
```

Thank you.

**Comment by Tlaster** [comment]
Sorry I'm busying doing my own job and bug fixes for PreCompose and any other things, you can try to do this yourself or asking ChatGPT :)

**Comment by mahramane** [comment]
Ok thank you 😢 good luck.
is PreCompose support Multiple back stacks?

**Comment by mahramane** [comment]
https://github.com/philipplackner/MultipleBackstacksCompose

**Comment by Tlaster** [comment]
PreCompose does support Nestesd `NavHost` with different `Navigator`.

**Comment by mahramane** [comment]
> PreCompose does support Nestesd `NavHost` with different `Navigator`.

Oh God

**Comment by mahramane** [comment]
When do you anticipate adding it to the library?

**Comment by Tlaster** [comment]
PreCompose already support Nestesd `NavHost` with different `Navigator`.
