### ISSUE TITLE
PreCompose doesn't work with Compose Multiplatform 1.6.0-rc02

### ISSUE THREAD

**Issue by armond1978** [Tlaster/PreCompose#272]
iOS build fails because of the issue discussed here:
https://github.com/JetBrains/compose-multiplatform/issues/4277
(Could not find "org.jetbrains.compose.annotation-internal:annotation")

It looks like PreCompose 1.6.0-beta02 utilizes Compose Multiplatform 1.6.0-beta02 and two of the internal dependencies of Compose Multiplatform (`org.jetbrains.compose.annotation-internal:annotation` and `org.jetbrains.compose.collection-internal:collection`) are binary incompatible with 1.6.0-rc01 and 1.6.0-rc02 which cause this issue.

Most probably upgrading Compose Multiplatform dependencies to the latest version will fix this.
More info: https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-rc01

**Comment by Tlaster** [comment]
Wait for koin to upgrade, see https://github.com/Tlaster/PreCompose/pull/251#issuecomment-1953327494

**Comment by sureshmaidaragi1919** [comment]
@Tlaster Koin updated the compose version 1.6.0-rc02 in this [3.6.0-wasm-alpha2](https://github.com/InsertKoinIO/koin/releases/tag/3.6.0-wasm-alpha2)

[Diff ] (https://github.com/InsertKoinIO/koin/compare/3.6.0-alpha1...3.6.0-wasm-alpha2#diff-46bb88d929c23161f27e7968f73bd6f3a3e6c6f50041ff1c0f10b7072c661e3fR23)

**Comment by Tlaster** [comment]
> @Tlaster Koin updated the compose version 1.6.0-rc02 in this [3.6.0-wasm-alpha2](https://github.com/InsertKoinIO/koin/releases/tag/3.6.0-wasm-alpha2)
> 
> [Diff](https://github.com/InsertKoinIO/koin/compare/3.6.0-alpha1...3.6.0-wasm-alpha2#diff-46bb88d929c23161f27e7968f73bd6f3a3e6c6f50041ff1c0f10b7072c661e3fR23)

You might got the wrong release, precompose 1.6.0-beta02 is [already using this version](https://github.com/Tlaster/PreCompose/compare/1.6.0-beta01...1.6.0-beta02#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR20)

**Comment by sureshmaidaragi1919** [comment]
we want precompose also should refere to the Jetbrains compose v1.6.0-rc02  instead Jetbrains compose v1.6.0-beta02

**Comment by sureshmaidaragi1919** [comment]
ho okay...
I think we should wait for Koin release ([3.6.0-wasm-alpha2](https://github.com/InsertKoinIO/koin/compare/3.6.0-alpha1...3.6.0-wasm-alpha2#diff-46bb88d929c23161f27e7968f73bd6f3a3e6c6f50041ff1c0f10b7072c661e3fR22))to get stable.

This is the error I am coming across 

`Could not find "org.jetbrains.compose.annotation-internal:annotation"`

**Comment by mahramane** [comment]
> Wait for koin to upgrade, see [#251 (comment)](https://github.com/Tlaster/PreCompose/pull/251#issuecomment-1953327494)

koin 3.6.0-alpha3 is out.

**Comment by Tlaster** [comment]
> > Wait for koin to upgrade, see [#251 (comment)](https://github.com/Tlaster/PreCompose/pull/251#issuecomment-1953327494)
> 
> koin 3.6.0-alpha3 is out.

But [not in maven yet](https://github.com/Tlaster/PreCompose/actions/runs/8167122562/job/22353429435?pr=251#step:4:705), so still waiting...

**Comment by mahramane** [comment]
> > > Wait for koin to upgrade, see [#251 (comment)](https://github.com/Tlaster/PreCompose/pull/251#issuecomment-1953327494)
> > 
> > 
> > koin 3.6.0-alpha3 is out.
> 
> But [not in maven yet](https://github.com/Tlaster/PreCompose/actions/runs/8167122562/job/22353429435?pr=251#step:4:705), so still waiting...

The koin-compose version is 1.2.0-alpha3

https://mvnrepository.com/artifact/io.insert-koin/koin-compose/1.2.0-alpha3

**Comment by Tlaster** [comment]
> > > > Wait for koin to upgrade, see [#251 (comment)](https://github.com/Tlaster/PreCompose/pull/251#issuecomment-1953327494)
> > > 
> > > 
> > > koin 3.6.0-alpha3 is out.
> > 
> > 
> > But [not in maven yet](https://github.com/Tlaster/PreCompose/actions/runs/8167122562/job/22353429435?pr=251#step:4:705), so still waiting...
> 
> The koin-compose version is 1.2.0-alpha3
> 
> https://mvnrepository.com/artifact/io.insert-koin/koin-compose/1.2.0-alpha3

Are you sure about that? 1.2.0-alpha3 was released in Mar 05, 2024.

**Comment by mahramane** [comment]
I also saw it in this issue :
https://github.com/InsertKoinIO/koin/issues/1634#issuecomment-1980928550

**Comment by Tlaster** [comment]
> I also saw it in this issue : [InsertKoinIO/koin#1634 (comment)](https://github.com/InsertKoinIO/koin/issues/1634#issuecomment-1980928550)

Kinda misleading...I thought koin would uses 3.6.0 as the version name.

**Comment by Tlaster** [comment]
fixed in 1.6.0 rc release
