### ISSUE TITLE
[BUG] rememberNavigator returns different instances inside and outside of NavHost

### ISSUE THREAD

**Issue by H4kt** [Tlaster/PreCompose#282]
**Describe the bug**
This is an attempt to reduce prop-drilling.
Calling `rememberNavigator()` before defining `NavHost` returns a different instance of `Navigator` than calling it inside the `NavHost`

**To Reproduce**
1. Get an instance of a navigator by calling `rememberNavigator()`
2. Define a `NavHost` using that `Navigator`
3. In a scene call `rememberNavigator()` again with the same name and compare navigators.

**Expected behavior**
I assume that the intended behavior is that it should return the same instance of the navigator

**Minimal reproducible example**
Reproduction sample which fails due to getting two different instances of `Navigator` object
```kotlin

PreComposeApp {

    val navigator = rememberNavigator()

    NavHost(
        navigator = navigator,
        initialRoute = "/"
    ) {

        scene("/") {
            val localNavigator = rememberNavigator()
            require(navigator === localNavigator)
        }

    }

}
```

**Comment by Tlaster** [comment]
This behavior is intentional, `rememberNavigator()` will return different instances of `Navigator`, a common use case is that PreCompose supports nested `NavHost`, which means that there are actually multiple instances of `Navigator`.

**Comment by H4kt** [comment]
> This behavior is intentional, `rememberNavigator()` will return different instances of `Navigator`, a common use case is that PreCompose supports nested `NavHost`, which means that there are actually multiple instances of `Navigator`.

Is there any way to workaround this?
I don't really want to prop-drill navigator to everywhere

**Comment by Tlaster** [comment]
> > This behavior is intentional, `rememberNavigator()` will return different instances of `Navigator`, a common use case is that PreCompose supports nested `NavHost`, which means that there are actually multiple instances of `Navigator`.
> 
> Is there any way to workaround this? I don't really want to prop-drill navigator to everywhere

You can have a CompositionLocal, or personally I recommend making the navigation event a callback, and call the navigator at the top level.
