### ISSUE TITLE
[BUG] 1.6.0-rc03 快速场景跳转没问题了，但随之而来的是，android端的返回键不能返回了

### ISSUE THREAD

**Issue by Matcha-xiaobin** [Tlaster/PreCompose#287]
**Describe the bug**
1.6.0-rc03 快速场景跳转没问题了，但随之而来的是，android端的返回键不能返回了。
android 14 + 预测性滑动返回是正常的。
通过点击按钮，调用navigator.goBack()，也是正常的。
这个问题看起来像是当前场景没有响应按下返回键。

**To Reproduce**
1. 跳转到下一个场景
2. 按下安卓手机上的虚拟返回键

**Expected behavior**
返回到上一个场景

**Minimal reproducible example**

**Comment by Matcha-xiaobin** [comment]
补充一下视频：
rc02
https://github.com/Tlaster/PreCompose/assets/5775066/d31e02c5-e81c-4b9a-8aca-472a7f21c1b8

rc03
https://github.com/Tlaster/PreCompose/assets/5775066/e9a51798-bac7-4990-b86f-0f0366d7b29c

**Comment by Tlaster** [comment]
确认了，在 https://github.com/Tlaster/PreCompose/pull/251/commits/62c5ed7a7505ed321d19276039ee2547e646e0fb 中做了修复，1.6.0-rc04发布会解决这个问题
