### ISSUE TITLE
Make ProvideDesktopCompositionLocals visibile to use different window object

### ISSUE THREAD

**Issue by ThraaxSession** [Tlaster/PreCompose#29]
Hi! I want to use another window (JBWindow) for different theming/styling, which suits more for me. I see that you wrap only the normal `Window` with this `ProvideDesktopCompositionLocals`. Can you make `ProvideDesktopCompositionLocals` and what it depends on visibile that I can use it to wrap my own window? Or do you have another approach, to use another different window object?

```kotlin
ProvideDesktopCompositionLocals(
        holder
    ) {
        Window(
            onCloseRequest = {
                holder.lifecycle.currentState = Lifecycle.State.Destroyed
                onCloseRequest.invoke()
            },
            state = state,
            visible = visible,
            title = title,
            icon = icon,
            undecorated = undecorated,
            transparent = transparent,
            resizable = resizable,
            enabled = enabled,
            focusable = focusable,
            alwaysOnTop = alwaysOnTop,
            onPreviewKeyEvent = onPreviewKeyEvent,
            onKeyEvent = onKeyEvent,
            content = {
                content.invoke(this)
            }
        )
    }
```

**Comment by Tlaster** [comment]
Make it open is ok, will add in the next release.
Meanwhile a quick workaround is just implementation `ProvideDesktopCompositionLocals` yourself, it does nothing but provide `LifecycleOwner`,`ViewModelStoreOwner`and`BackDispatcherOwner`

**Comment by ThraaxSession** [comment]
Do you have a small example? Else i wait for the next release :)

**Comment by Tlaster** [comment]
You can just copy && paste [here](https://github.com/Tlaster/PreCompose/blob/89b869270bada05d35ac60d27356c8884622c001/precompose/src/jvmMain/kotlin/moe/tlaster/precompose/PreComposeWindow.kt#L84-L110).

**Comment by ThraaxSession** [comment]
Thanks! This worked well! :) just another question @Tlaster does it work with Android too?

**Comment by ThraaxSession** [comment]
Got it! :) All works!
