### ISSUE TITLE
[BUG] [Android] NavHost launching the initial route twice!

### ISSUE THREAD

**Issue by armond1978** [Tlaster/PreCompose#290]
**Describe the bug**
It looks like on Android, NavHost is launching the initial route twice. But this doesn't happen on Native. It works just fine.

I've tested with Precompose 1.6.0-rc01, rc02, rc03, rc04 and rc05. They all have the same bug.

**Expected behavior**
The initial route should be launched just once

**Minimal reproducible example**
```
@Composable
fun AppNavigation() {
    val navigator = rememberNavigator()

    NavHost(
        modifier = modifier.fillMaxSize(),
        navigator = navigator,
        initialRoute = "/initial-route"
    ) {
        scene("/initial-route") {
             println(">>>>> /initial-route")
             Text("Initial Route")
       }
    }
}
```

**Comment by Tlaster** [comment]
Sorry I can not reproduce this issue, can you provide more complete example code for this?

**Comment by armond1978** [comment]
@Tlaster I've attached a very simple project demonstrating this behavior. This project utilizes jetbrains compose libraries and material3. All the code is in `MainActivity.kt` (Android) and `App.kt` (commonMain); and I've added `println`s so that you can track the recompositions easily. Looks like when the NavHost is re-composed for a second time (because of the code structure, edge-to-edge design or some other factors), the initial route is called once again although it has already re-routed to another screen and the initial route itself shouldn't be active anymore (check for the printed ">>>" lines on LogCat).
[PreCompose Test.zip](https://github.com/Tlaster/PreCompose/files/14738623/PreCompose.Test.zip)

**Comment by Tlaster** [comment]
You need to call `enableEdgeToEdge()` before `super.onCreate` according to the doc: https://developer.android.com/develop/ui/views/layout/edge-to-edge#enable-edge-to-edge-display, once you've done that, the issue resolved.
BTW the sample you provided call `PreComposeApp` twice.

**Comment by armond1978** [comment]
I've simplified the logic on `enableEdgeToEdge()` side for this test project. I have to do it inside the compose function because I have no other choice to handle the light/dark background change for system status bar (it doesn't automatically adapt according to the current background). I found another workaround to avoid the second composition. Thanks for looking into this.
