### ISSUE TITLE
[BUG] koinViewModel in precompose-koin not consistent across platform

### ISSUE THREAD

**Issue by reginaldlouis** [Tlaster/PreCompose#292]
In `precompose-koin` version 1.6, for **jvm**, just calling `koinViewModel<BudgetViewModel>()` work, but for **wasmJs**  I get this error:
```
No value passed for parameter 'vmClass'
```

When digging into `precompose-koin`, I can see that `koinViewModel` has 2 different signatures.

In `commonMain/kotlin/moe/tlaster/precompose/koin/Koin.kt` the signature is:
```
fun <T : ViewModel> koinViewModel(
    vmClass: KClass<T>,
    qualifier: Qualifier? = null,
    stateHolder: StateHolder = checkNotNull(LocalStateHolder.current) {
        "No StateHolder was provided via LocalStateHolder"
    },
    key: String? = null,
    scope: Scope = LocalKoinScope.current,
    parameters: ParametersDefinition? = null,
): T
```

And in `jvmAndroidMain/kotlin/moe/tlaster/precompose/koin/Koin.jvmAndroid.kt` the signature is:
```
inline fun <reified T : ViewModel> koinViewModel(
    qualifier: Qualifier? = null,
    stateHolder: StateHolder = checkNotNull(LocalStateHolder.current) {
        "No StateHolder was provided via LocalStateHolder"
    },
    key: String? = null,
    scope: Scope = LocalKoinScope.current,
    noinline parameters: ParametersDefinition? = null,
): T
```

No need to pass a `vmClass: KClass<T>` parameter. Why not have a consitent api across platform?

**Comment by Tlaster** [comment]
Because there's a bug for Kotlin/Native with Compose: https://github.com/JetBrains/compose-multiplatform/issues/3147, the doc dose mention this in [here](https://github.com/Tlaster/PreCompose/blob/master/docs/component/view_model.md#:~:text=NOTE%3A%20If%20you%27re%20using%20Kotlin/Native%20target%2C%20please%20use%20viewModel%20with%20modelClass%20parameter%20instead).

**Comment by reginaldlouis** [comment]
Thx

/RL

**Comment by Tlaster** [comment]
> Looks like the bug was fixed? [JetBrains/compose-multiplatform#3147](https://github.com/JetBrains/compose-multiplatform/issues/3147)

Seems like the fix is included in compose compiler 1.5.10.2, so we can get generic inline composable function now!

**Comment by ColtonIdle** [comment]
@Tlaster seems like androidx now supports kmp lifecycle, navigation and viewmodel (at least in the alphas). Plans to wind down this library?

**Comment by Tlaster** [comment]
> @Tlaster seems like androidx now supports kmp lifecycle, navigation and viewmodel (at least in the alphas). Plans to wind down this library?

I haven't decided yet, but since Google and Jetbrains officially releasing ViewModel and Navigation for multiplatform, maybe PreCompose have done its job.

**Comment by ColtonIdle** [comment]
🫡

Sent from Proton Mail Android

-------- Original Message --------
