### ISSUE TITLE
Question: How to share the state inside a viewmodel over different scenes

### ISSUE THREAD

**Issue by ThraaxSession** [Tlaster/PreCompose#30]
Hi, just another question.
When I create a ModelView with different props (MutableStateOf) and I fill this model from scene1.. and initialize this ModelView in scene2, the state is getting lost. Can you tell me what is the proper way to share the state? 

Thank you!

**Comment by Tlaster** [comment]
State sharing between scenes is not supported at this time, but you can have a repository layer that stores the data.

**Comment by ThraaxSession** [comment]
Is it planned for the future to handle states? I mean if I handle username or a counter, a repository doesn't make sense

**Comment by tiper** [comment]
@ThraaxSession,

You could consider creating the view model before and pass it to the scenes as a parameter.
```
val navigator = rememberNavigator()
val sharedViewModel = viewModel(MyViewModel::class)

NavHost(
    navigator = navigator,
    initialRoute = "/A",
) {
    scene(route = "/A") {
        SceneA(viewModel = sharedViewModel)
    }
    scene(route = "/B", navTransition = enterTransitionFromRight) {
        SceneB(viewModel = sharedViewModel)
    }
}
```

**Comment by ThraaxSession** [comment]
@tiper :) That's a good idea for now!

**Comment by tiper** [comment]
@ThraaxSession No problem.

If you don't want to pass around view models another approach is to wrap your composable and provide them the same ViewModelStore.

Something like this
```
val navigator = rememberNavigator()
val viewModelStoreOwner = LocalViewModelStoreOwner.current

NavHost(
    navigator = navigator,
    initialRoute = "/A",
) {
    scene(route = "/A") {
        CompositionLocalProvider(
            LocalViewModelStoreOwner provides viewModelStoreOwner,
        ) {
            SceneA()
        }
    }
    scene(route = "/B") {
        CompositionLocalProvider(
            LocalViewModelStoreOwner provides viewModelStoreOwner,
        ) {
            SceneA()
        }
    }
}
```

You can also create an extension to make it more elegant and instead of always wrapping each composable you just call your own extension:

```
fun RouteBuilder.scene(
    viewModelStoreOwner: ViewModelStoreOwner,
    route: String,
    deepLinks: List<String> = emptyList(),
    navTransition: NavTransition? = null,
    content: @Composable (BackStackEntry) -> Unit,
) {
    scene(route = route, deepLinks = deepLinks, navTransition = navTransition) {
        CompositionLocalProvider(
            LocalViewModelStoreOwner provides viewModelStoreOwner,
        ) {
            content(it)
        }
    }
}

...

val navigator = rememberNavigator()
val viewModelStoreOwner = LocalViewModelStoreOwner.current

NavHost(
    navigator = navigator,
    initialRoute = "/A",
) {
    scene(route = "/A", viewModelStoreOwner = viewModelStoreOwner) {
        SceneA()
    }
    scene(route = "/B", viewModelStoreOwner = viewModelStoreOwner) {
        SceneB()
    }
}
```

**Comment by ThraaxSession** [comment]
@tiper  that's an awesome idea and much more elegant! I'll try it this week, thank you!

**Comment by ThraaxSession** [comment]
Again thanks! It works. :) Though, I have been careful now as the state is always shared. But that's fine.
