### ISSUE TITLE
The window cannot be displayed according to the size of the content

### ISSUE THREAD

**Issue by artillerymans** [Tlaster/PreCompose#31]
![image](https://user-images.githubusercontent.com/16060581/226879767-a96cec0f-3328-4e04-b13f-89c1b449e6ee.png)
The above screenshot is the effect after the code has been run

![image](https://user-images.githubusercontent.com/16060581/226880464-d88a8015-3663-4f8e-b9bf-37b6a84fb906.png)

Normally I think it should be like this

**Comment by Tlaster** [comment]
This is by design, you can adjust window size by content using custom layout.

**Comment by artillerymans** [comment]
有类似android中的 wrap_content的效果吗? 
Is there an effect similar to wrap_content in android?

**Comment by Tlaster** [comment]
No, this is not how Compose for Desktop works.

**Comment by Tlaster** [comment]
Close as inactive
