### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by artillerymans** [Tlaster/PreCompose#32]
![image](https://user-images.githubusercontent.com/16060581/227409703-ea2e9371-c04a-4fe6-90c2-2d0763433a17.png)
我少依赖了什么库吗?

**Comment by artillerymans** [comment]
解决了
https://github.com/cashapp/molecule 按照这个添加插件依赖
![image](https://user-images.githubusercontent.com/16060581/227416721-e3422b4d-11d8-44e0-931a-407884584f3e.png)
![image](https://user-images.githubusercontent.com/16060581/227416752-aa346456-a3dd-48df-8178-54edff12c0ec.png)
成功运行

**Comment by Tlaster** [comment]
Close as resolved
