### ISSUE TITLE
No more update?

### ISSUE THREAD

**Issue by NakiriYuuzu** [Tlaster/PreCompose#320]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tlaster** [comment]
I do have some plan on update(such as migrate to Jetpack's ViewModel and Lifecycle), but currently I'm busy doing my own job.

**Comment by NakiriYuuzu** [comment]
> I do have some plan on update(such as migrate to Jetpack's ViewModel and Lifecycle), but currently I'm busy
