### ISSUE TITLE
scene invoked twice when used the variable navigation 

### ISSUE THREAD

**Issue by N7ghtm4r3** [Tlaster/PreCompose#338]
**Describe the bug**
Hi, when I use the [variable navigation](https://github.com/Tlaster/PreCompose/blob/master/docs/component/navigation.md#variable) the invocation of the current `scene` is invoked twice and this cause a double recomposition of that scene

**To Reproduce**
1. Create a Compose Multiplatform project
2. Edit the `App()` method with the snippet here below
3. See error in the console where will be printed `Hi` two times

**Expected behavior**
Single invocation of the `scene`, so `Hi` printed only once

**Minimal reproducible example**
```kotlin
PreComposeApp {
    val navigator = rememberNavigator()
    NavHost(
        navigator = navigator,
        initialRoute = "initial_route"
    ) {
        scene(
            route = initial_route
        ) {
            // content
        }
        scene(
            route = "any_route_path/{$any_id}"
        ) { backstackEntry ->
            // using 
           backstackEntry.pathMap[any_id]
           // for example
           println("Hi")
           // the content of this scene will be invoked twice and related its recomposition
        }
    }
}
```

**Comment by Tlaster** [comment]
Duplicate with #162 , but the fix in that PR is not working for current version, I still try to find a way to avoid unnecessary recomposition.

**Comment by N7ghtm4r3** [comment]
Thank you for the info!

**Comment by N7ghtm4r3** [comment]
Hi, any updates about this issue?

**Comment by Tlaster** [comment]
No update yet, since compose multiplatform 1.7 is around the corner, I need to migrate to the compose 1.7 first, which might not be an easy work since `SeekableTransitionState` API has changed since 1.7.

**Comment by N7ghtm4r3** [comment]
This behavior not happens in the `1.7.0-alpha03` version
