### ISSUE TITLE
我不是很明白,但是我看源代码里面确实用了dispatcher.main ,当前我只是在PC端运行

### ISSUE THREAD

**Issue by artillerymans** [Tlaster/PreCompose#34]
![image](https://user-images.githubusercontent.com/16060581/229414153-b59b9e0d-1a10-458d-ba87-e7ac910653c6.png)

val (state, bus) = rememberPresenter { LoginVerifyPresenter(it) }

![image](https://user-images.githubusercontent.com/16060581/229414290-ee71c17a-5326-473e-a25f-8c6516c8695f.png)
![image](https://user-images.githubusercontent.com/16060581/229414341-5a88d721-42e8-4825-b38b-1e0d52c12538.png)
![image](https://user-images.githubusercontent.com/16060581/229414400-dff8db26-de0e-4072-8e0d-09c0afe8cae9.png)
以上是我的大致代码

**Comment by artillerymans** [comment]
我当前的处理方案:
![image](https://user-images.githubusercontent.com/16060581/229425132-87b027bb-eae2-463b-a6e7-bdac97b92556.png)
当前运行目测没有发现其他的问题

**Comment by Tlaster** [comment]
Hi, can you check if version 1.4.0 works for you?

**Comment by artillerymans** [comment]
![image](https://user-images.githubusercontent.com/16060581/232947311-b6908ecb-9026-4da1-b5db-84cbaa6eb0dd.png)
这个是用1.4.0后的错误信息
我用的jdk17 这个是否有影响？

**Comment by huhu2008** [comment]
> ![image](https://user-images.githubusercontent.com/16060581/232947311-b6908ecb-9026-4da1-b5db-84cbaa6eb0dd.png) 这个是用1.4.0后的错误信息 我用的jdk17 这个是否有影响？

一样的问题  这个有解决吗  我用的jdk15

**Comment by gitzhan** [comment]
使用环境：compose-desktop [single platform]
遇到同样的问题，刚开始是下了大神的源码去用解决的，后来仔细看了下，实际上是找不到【app.cash.molecule.RecompositionClock】这个类（这个类在molecule-runtime包内），跟providePlatformDispatcher以及jdk17啥的都没关系。再看precompose-molecule实现，其是编译时依赖了这个包（ compileOnly("app.cash.molecule:molecule-runtime:0.9.0")），所以大家直接在自己的项目中，增加这个依赖就可以了（如：implementation("app.cash.molecule:molecule-runtime:0.9.0")）。
这里答复下，帮助更多人。
这是作者源码里的：
![image](https://github.com/Tlaster/PreCompose/assets/24983630/bc63d458-acbe-462a-a291-4497c0d98ae2)
这是我使用的：
![image](https://github.com/Tlaster/PreCompose/assets/24983630/c291796f-08a0-46ee-b701-3642d269570f)

**Comment by Tlaster** [comment]
close as completed
