### ISSUE TITLE
[BUG] iOS Compile failed

### ISSUE THREAD

**Issue by briandr97** [Tlaster/PreCompose#348]
**Describe the bug**
I really want to use PreCompose for navigation.
On android it works well but when I compile on xcode, compile is failed.
In my main project, I get several compile errors.
`KLIB resolver: Could not find "molecule:molecule-runtime" in [/Users/brian/AndroidStudioProjects/Fitapat/composeApp, /Users/brian/.konan/klib, /Users/brian/.konan/kotlin-native-prebuilt-macos-aarch64-2.0.0/klib/common, /Users/brian/.konan/kotlin-native-prebuilt-macos-aarch64-2.0.0/klib/platform/ios_simulator_arm64]`

`Process 'command '/Library/Java/JavaVirtualMachines/{java version}/Contents/Home/bin/java'' finished with non-zero exit value 1`

I changed my java version three times (11, 17, 22) But all failed.
I can't find the reason (maybe I guess it is because of other dependencies).

So I make new Project to find what dependency is wrong.
But iOS compile error occurred like this image.
![image](https://github.com/user-attachments/assets/b366cd56-5b87-4ad4-947c-e555ceca8aed)

**To Reproduce**
Please help me 🙏🙏
I've been suffering from this problem for several days.

**Comment by Tlaster** [comment]
If you're using precompose-molecule, make sure you've setup molecule dependency correctly https://github.com/cashapp/molecule

**Comment by briandr97** [comment]
@Tlaster 
I only add `api("moe.tlaster:precompose:1.6.1")` not molecule, and I just got following errors 😭
<img width="967" alt="image" src="https://github.com/user-attachments/assets/3f162915-1247-443c-a074-68bb1cea144e">

And these are my commonMain dependencies
<img width="539" alt="image" src="https://github.com/user-attachments/assets/3dd7905b-9143-4eca-bc72-a5e191c1a712">
<img width="530" alt="image" src="https://github.com/user-attachments/assets/cb1c6a82-d9e6-4d5d-a5fc-93a3e23b669f">

**Comment by Tlaster** [comment]
Might be the same error with #342
