### ISSUE TITLE
UIKit native navigation support

### ISSUE THREAD

**Issue by alexzhirkevich** [Tlaster/PreCompose#35]
Hey.

Compose multiplatform 1.4 will support uikit-to-compose interop. Do you have plans to implement something like `NativeNavHost` with `UINavigationController` under the hood?

I made it in about 100 lines of code. Here is the result. Looks almost native except of material views :)

Btw, your library is awesome, thanks for it

https://user-images.githubusercontent.com/63979218/231277302-1a7972d4-42bc-4dab-9b6a-8d041db811bf.mp4

**Comment by Tlaster** [comment]
Wow! awesome! I was thinking about implementing a compose based swipe back navigation, but using `UINavigationController` is a brand new way I had never thought of!
This may break the `NavTransition`, but most importantly this works seamlessly on iOS.
I might be busy lately, can you submit a PR?

**Comment by alexzhirkevich** [comment]
Yeah, this completely ignores nav transition, but I suppose iOS devs have never heard about it :). For those who have, default navhost is still here. Migration needs only rename NavHost->NativeNavHost. Code is too raw for PR I guess and uses RC version of compose. I will make a PR a little bit later.

I also playing with something like native navhost for browser using hash router. Like navhost routes are duplicated to browser input line like example.com/#/home and vice versa. It helps persist route after page reload and have bookmarks fore example directly to profile screen or something

**Comment by shubhamsinghmutualmobile** [comment]
This is great work @alexzhirkevich 👏  Would love to see a PR soon 🌟

**Comment by alexzhirkevich** [comment]
@shubhamsinghmutualmobile 
Multiplatform swipe back navigation added in #38. Native one have some bugs and limitations now

**Comment by ti4n1993** [comment]
waiting for the new version

**Comment by Tlaster** [comment]
It's now live in 1.4.1🎉
