### ISSUE TITLE
[BUG] Recomposition with state.collectAsStateWithLifecycle()

### ISSUE THREAD

**Issue by thebordev** [Tlaster/PreCompose#350]
Hi, I don't know if this is a bug. I want to clarify the behavior, when I update the state, the entire PinScreen is recomposed.
If you leave only the state in the pin screen dependencies, the screen will still be recomposed.

App composable
`
@Composable
fun App() {
    PreComposeApp {
        SccDefaultTheme {
            MainScreen()
        }
    }
}
`

@Composable
internal fun MainScreen(
    modifier: Modifier = Modifier,
    viewModel: MainViewModel = koinViewModel(vmClass = MainViewModel::class),
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val initialRoute = remember { viewModel.getInitialRoute() }
    val navigator = rememberNavigator()
    Scaffold { paddings ->
        NavHost(
            navigator = navigator,
            initialRoute = initialRoute,
        ) {

scene(route = pinScreenRoute) { bse ->
                PinScreen(
                    navigator = navigator,
                    modifier = Modifier.safeDrawingPadding(),
                    mainViewModel = viewModel,
                )
            }
}

@Composable
internal fun PinScreen(
    navigator: Navigator,
    modifier: Modifier = Modifier,
    mainViewModel: MainViewModel,
    viewModel: PinViewModel = koinViewModel(vmClass = PinViewModel::class),
) {
   val state by viewModel.state.collectAsStateWithLifecycle()

PinBoard(
                isBiometricAvailable = state.isBiometricAvailable,)
}

In viewModel 
internal val state = MutableStateFlow(PinState())

state.update {..}

compose metrics
<img width="904" alt="Снимок экрана 2024-07-16 в 19 17 00" src="https://github.com/user-attachments/assets/11453736-373d-46e6-85a2-3cbbda1fef86">
<img width="407" alt="Снимок экрана 2024-07-16 в 19 17 39" src="https://github.com/user-attachments/assets/6f1c27ca-e78c-40f2-98bd-0c81ecba9e98">

Layout Inspector
<img width="435" alt="Снимок экрана 2024-07-16 в 19 22 58" src="https://github.com/user-attachments/assets/e5ff6fe2-ac6f-4c7e-829c-9a787ad17c21">

**Comment by Tlaster** [comment]
`collectAsStateWithLifecycle` is essentially a copy and paste from the official source code, so its behavior should be identical if you're using the official version. It might be better to leave only the state in the pin screen dependencies to avoid recomposition.

**Comment by thebordev** [comment]
Yes, with official libs the screen is recomposed in the same way. Feels strange..
