### ISSUE TITLE
ViewModel always creating a new one

### ISSUE THREAD

**Issue by QiXi** [Tlaster/PreCompose#37]
An example of use when the viewModel is re-created, since the owner of the BackStackEntry always changes. so never works ViewModelStoreOwner.getViewModel
```
NavHost(
        navigator = navigator, initialRoute = startDestination, modifier = modifier
    ) {
        scene(HOME_ROUTE) {    <- there is always a new viewModelStoreOwner
            val viewModel = viewModel(HomeViewModel::class) {
                HomeViewModel(appContainer)
            }
            HomeView(viewModel)
        }
    }
```

**Comment by Tlaster** [comment]
Hi, can you provide more information or an example project that reproduce this bug? I've check the todo sample and it's working for me.

https://user-images.githubusercontent.com/8370277/232263582-b3377826-ff59-427c-b6b6-07c98085cc6b.mp4

**Comment by QiXi** [comment]
```
class NoteListViewModel : ViewModel() {
    init {
        println("NoteListViewModel instance ${this.hashCode()}")
    }
...
```
```
class NoteEditViewModel(
    private val id: Int?,
) : ViewModel() {
    init {
        println("NoteEditViewModel instance ${this.hashCode()}")
    }
...
```

```
@Composable
fun App() {
    val navigator = rememberNavigator()
...
NoteEditScene(
 id = id,
 onDone = {
      navigator.goBack()
 },
 onBack = {
     navigator.navigate("/home")
     //navigator.goBack()
 }
 )
```
Before switching to PreCompose, I used androidx.navigation
```
composable("/home") {
val viewModel: HomeViewModel = viewModel(factory = HomeViewModel.provideFactory(...))
```
and there the viewModel was not created again. Therefore, I expected the same behavior after switching to PreCompose.

[17.04.2023 16:51:42.webm](https://user-images.githubusercontent.com/1622824/232509516-502ed8ff-dfb8-4ea5-bd83-9a4ac26386fa.webm)

**Comment by Tlaster** [comment]
You use `navigator.navigate("/home")` instead of `navigator.goBack()` in NoteEditScene's onBack callback, which navigates to a new route and eventually creates a new instance of HomeViewModel, that's by design. If you want to navigate to the home while keeping the HomeViewModel as a single instance, you can use `navigator.navigate("/home", options = NavOptions(launchSingleTop = true))`.

**Comment by QiXi** [comment]
Thank you. It would be nice to be able to see the back stack of state routes while developing, debugging, and learning how to use the library. For example, the ability to observe the current position as a string "/home/page1/page2" and so on.
