### ISSUE TITLE
[BUG]  Dialog back navigation

### ISSUE THREAD

**Issue by N7ghtm4r3** [Tlaster/PreCompose#383]
**Describe the bug**
Hi, I'm using the `PreCompose` library in a `KMP` project, my `NavHost` is the following:

```kotlin
NavHost(
    navigator = navigator,
    initialRoute = SPLASH_SCREEN
) {
    scene(
        route = SPLASH_SCREEN
    ) {
        Splashscreen().ShowContent()
    }
    dialog(
        route = PROFILE_DIALOG
    ) {
        DialogScreen(
            dialogScreen = ProfileScreen()
        )
    }
    scene(
        route = PROJECTS_SCREEN
    ) {
        ProjectsScreen().ShowContent()
    }
}
```
From the `PROJECTS_SCREEN` I should navigate to the `PROFILE_DIALOG` (the `dialog`) and then invoking the `navigator.goBack()` to navigate to the past `scene`  (`PROJECTS_SCREEN`) it seems not re-invoking that scene actually but just pop the dialog instead. May I'm wrong to back navigate from a `dialog`? Because if it changes from `dialog` to `scene` correctly works

**Expected behavior**
When navigate back from the `dialog` re-invoking the previous `scene`

**Minimal reproducible example**
The setup of `NavHost`

**Comment by Tlaster** [comment]
Thank you for reporting this issue. If I understand correctly, the steps to reproduce are:
1. Navigate to the PROFILE_DIALOG
2. Use navigator.goBack()

I tried to replicate this behavior using the todo sample project in PreCompose, but I wasn't able to reproduce the issue you described. The navigation seems to work as expected in that sample.
Can you provide more information about this issue? a reproducible example could be better.

**Comment by N7ghtm4r3** [comment]
Yes the navigation works correctly, so the navigator navigates to the previous `scene`, but it seems does not recompose that scene, but just navigates to it. Can you try to use [EquinoxScreen](https://github.com/N7ghtm4r3/Equinox-Compose/blob/main/documd%2FEquinoxScreen.md) and see the lifecycle logs? I suggest you to use with desktop target because there will be only that specifics lifecycle logs

**Comment by N7ghtm4r3** [comment]
Hi, I have create a little demonstrative demo and invited you to the repository @Tlaster if you have time to check it of course

**Comment by Tlaster** [comment]
Sorry for the late reply.
> but it seems does not recompose that scene, but just navigates to it
This is by design, and it should not trigger any recomposition, since currently the NavHost behave like this:
```Kotlin
Box {
    Scene()
    if (dialog) {
        Dialog()
    }
}
```
So if you navigate back from the dialog, it just remove the dialog from the composition tree, but the scene is still there which remain unchanged, so it should not trigger any recomposition.

**Comment by N7ghtm4r3** [comment]
No problem, thank you for the info and the help
