### ISSUE TITLE
Migration guide from 1.3.0 to 1.4.0

### ISSUE THREAD

**Issue by ThraaxSession** [Tlaster/PreCompose#41]
Hi together,

I have issues to migrate to 1.4.0. Like with `val viewModelStoreOwner = LocalViewModelStoreOwner.current`
Do you have a complete guide or can create one?

**Comment by Tlaster** [comment]
The whole ViewModel is now in a separate library: `moe.tlaster.precompose-viewmodel`.
And `ViewModelStoreOwner` has been removed and replaced by `moe.tlaster.precompose.stateholder.StateHolder` which is similar to `ViewModelStoreOwner` but does more and does not need the `precompose-viewmodel` library,

**Comment by ThraaxSession** [comment]
`ViewModelStoreOwner` is equal to `LocalViewModelStoreOwner`?
ViewModel was easy to adapt.

**Comment by Tlaster** [comment]
`LocalViewModelStoreOwner` is just a composition local of `ViewModelStoreOwner`.
The limitation of `ViewModelStoreOwner` is that it only applies to ViewModel, `StateHolder` can apply to any type and also react to the lifecycle if the target type implements Kotlin's `AutoCloseable`, so as of 1.4.0 PreCompose uses `StateHolder` as a replacement for `ViewModelStoreOwner`.

**Comment by Tlaster** [comment]
close as inactive
