### ISSUE TITLE
"Module with the Main dispatcher is missing" exception on Desktop build when using viewModelScope

### ISSUE THREAD

**Issue by cmota** [Tlaster/PreCompose#5]
Hello!

This is working fine on Android, but I've noticed that if I compile my app for Desktop, the following call inside a ViewModel:

```
viewModelScope.launch {
   _images.value = items
}
```

Will trigger the exception:

```
java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
```

I've managed to fix the issue by updating the **build.gradle.kts** file to:

```
val jvmMain by getting {
  dependencies {
    dependsOn(commonMain)

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.6.1")
  }
}
```

**Comment by Tlaster** [comment]
It seems that the JVM target requires adding the `org.jetbrains.kotlinx:kotlinx-coroutines-swing ` dependency, I will fix that.

**Comment by Tlaster** [comment]
Closing as fixed
