### ISSUE TITLE
大佬，是否考虑支持下配置默认routeView不？即：若不存在支持的route Scene，则导航至一个默认的SceneView

### ISSUE THREAD

**Issue by gitzhan** [Tlaster/PreCompose#51]
RT，
如：
![image](https://github.com/Tlaster/PreCompose/assets/24983630/efaa0cd5-1e32-4d5c-b738-4d1ad67a560f)

**Comment by Tlaster** [comment]
[route支持正则](https://github.com/Tlaster/PreCompose/blob/master/docs/component/navigation.md#regex)，你可以
```
scene(
    route = "*"
)
```

**Comment by Tlaster** [comment]
close as inactive
