### ISSUE TITLE
iosApp build problem

### ISSUE THREAD

**Issue by Krakert** [Tlaster/PreCompose#54]
I keep getting:

```
Cannot access 'kotlin.AutoCloseable' which is a supertype of 'com.triple.pokemon.presentation.overview.PokemonOverviewViewModel'. Check your module classpath for missing or conflicting dependencies
```

When make a simple ViewModel, what is going wrong?
I'm using version `1.4.2` with compose multiplatform `1.4.0`

**Comment by Tlaster** [comment]
Which version of Kotlin you're using for your project? `kotlin.AutoCloseable` requires Kotlin 1.8.20.

**Comment by Tlaster** [comment]
close as inactive
