### ISSUE TITLE
initialRoute doesn't work when it has parameters

### ISSUE THREAD

**Issue by hichamboushaba** [Tlaster/PreCompose#63]
When defining a NavHost, if we supply the `initialRoute` with some parameters, the app crashes with the error: `No initial route target fot this route graph`, and the cause is this line which compares the initial route to the routes templates: https://github.com/Tlaster/PreCompose/blob/fb65985d99dcacbe9f057df42c061958212f5e43/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt#L102-L104

I wanted to fix this with the PR #62, but I'm not sure what's the best approach to take here, using the RouteParser for the validation seems like an overkill, and IMO the check is not important, since the app would crash in all cases if the `initialRoute` doesn't match another route, so probably it can simply be removed completely, WDYT?

**Comment by Tlaster** [comment]
Yes, the check is not that important, you can just remove it in #62 
I was just wondering in what use case you would need an initial route with parameters, since you cannot pass parameters to the initial route.

**Comment by hichamboushaba** [comment]
> I was just wondering in what use case you would need an initial route with parameters, since you cannot pass parameters to the initial route.

I use a nested NavHost to support multistacks, and it works well, for some screens I need to pass some arguments to the initial screen in the nested stack, for now I'm using a workaround of defining a dummy screen as the initial screen, then starting a navigation using `LaunchedEffect` to the actual screen with parameters, so with this fix, I won't need this workaround.
