### ISSUE TITLE
如何在在compose-multiplatform-ios-android-template中集成

### ISSUE THREAD

**Issue by iamcyw** [Tlaster/PreCompose#65]
能不能指导下如何在使用 [[compose-multiplatform-ios-android-template](https://github.com/JetBrains/compose-multiplatform-ios-android-template)](https://github.com/JetBrains/compose-multiplatform-ios-android-template/tree/main) 中集成PreCompose

**Comment by Tlaster** [comment]
请参考[文档](https://github.com/Tlaster/PreCompose/blob/master/docs/setup.md)

**Comment by Tlaster** [comment]
close as inactive
