### ISSUE TITLE
I can't run on IOS 

### ISSUE THREAD

**Issue by hamidfathi1998** [Tlaster/PreCompose#66]
I clone your samples and run on android but I can't run on IOS, can you help me?

**Comment by Tlaster** [comment]
To run samples on iOS, you need to run `./gradlew :samples:todo:ios:iosDeploySimulatorDebug` since the samples are using old iOS project structure.

**Comment by hamidfathi1998** [comment]
If you want I can change the IOS structure. to contribute in your project.

**Comment by Tlaster** [comment]
PR is always welcome, you can submit a PR that change to the new project structure.

**Comment by Tlaster** [comment]
close as inactive
