### ISSUE TITLE
Kotlin 1.9.0

### ISSUE THREAD

**Issue by mahramane** [Tlaster/PreCompose#67]
Kotlin 1.9.0 came.
Please use Kotlin 1.9.0.

**Comment by Tlaster** [comment]
Blocked by https://github.com/JetBrains/compose-multiplatform/issues/3323

**Comment by Lavmee** [comment]
> Blocked by https://github.com/JetBrains/compose-multiplatform/issues/3323

Compose Multiplatform 1.4.2 now supports Kotlin 1.9.0
