### ISSUE TITLE
Access Navigator outside of a Composable block

### ISSUE THREAD

**Issue by alexeiartsimovich** [Tlaster/PreCompose#68]
Hello,

First of all, thanks for this amazing lib.

I need help in the following use case:

- I have `NavHost` declared as in your sample. It contains a couple of scenes.
- Part of the business logic is in Swift. Based on a condition, I need to navigate to a scene from Swift code.

For this purpose, I wrote a function `navigateToMainScreen` in iosMain - it is called from Swift. 

Now I need to access the Navigator instance in this function. How can I do this?

**Comment by Tlaster** [comment]
You can have a navigator on the top level and call it, for example:
```Kotlin
val navigator by lazy {
    Navigator()
}

fun navigateToMainScreen() {
    // do something with navigator
}
```
And ensure you `NavHost` uses this navigator.
