### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by alexzhirkevich** [Tlaster/PreCompose#69]
It'd be great to heave a wasm support. May be in a different experimental branch

**Comment by Tlaster** [comment]
Seems like compose for wasm support is in different maven repo (https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental) and have different version, it's better to have a different branch to do it.

**Comment by FunkyMuse** [comment]
https://blog.jetbrains.com/kotlin/2023/12/kotlin-for-webassembly-goes-alpha/

**Comment by ismai117** [comment]
please support wasm

**Comment by Tlaster** [comment]
Since [compose-multiplatform 1.6.0-alpha01](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-alpha01) comes with wasm support, I'll add this support as an alpha version.

**Comment by Tlaster** [comment]
Koin does not support wasm target yet (see https://github.com/InsertKoinIO/koin/issues/1634), I'd like to wait for it.

**Comment by mahramane** [comment]
> Koin does not support wasm target yet (see [InsertKoinIO/koin#1634](https://github.com/InsertKoinIO/koin/issues/1634)), I'd like to wait for it.

Hi
koin `3.6.0-wasm-alpha1` is out.

**Comment by Tlaster** [comment]
Still no wasm support for [Koin Compose](https://github.com/InsertKoinIO/koin/blob/7c1c8712a46fd8bbe72f568bab3a2124b2ed7b5e/compose/koin-compose/build.gradle#L7-L20) for now, which is the dependency for precompose-koin.

**Comment by Tlaster** [comment]
> > Still no wasm support for [Koin Compose](https://github.com/InsertKoinIO/koin/blob/7c1c8712a46fd8bbe72f568bab3a2124b2ed7b5e/compose/koin-compose/build.gradle#L7-L20) for now, which is the dependency for precompose-koin.
> 
> @Tlaster they have the `koin-compose` artifact listed on their documentation site as part of the [`3.6.0-wasm-alpha1` ](https://insert-koin.io/docs/setup/koin) and it is listed on [Maven Central](https://mvnrepository.com/artifact/io.insert-koin/koin-compose/3.6.0-wasm-alpha1) too.
> 
> However when I browse their code on the [`3.6.0-wasm-alpha1` tag ](https://github.com/InsertKoinIO/koin/blob/3.6.0-wasm-alpha1/projects/compose/koin-compose/build.gradle.kts) I also don't see `wasmJs` listed. How is this possible did they make a mistake somewhere and is the wasm artifact in Maven Central non-functional? Or is there some Gradle magic that we're missing?
> 
> I'm not really a Koin user, but I'm having a look to see what's going on here.

Not sure what's happening, if using `io.insert-koin:koin-compose:3.6.0-wasm-alpha1` with wasmJs target, it will throw an exception in gradle: `No matching variant of io.insert-koin:koin-compose:3.6.0-wasm-alpha1 was found`.

**Comment by mahramane** [comment]
> Still no wasm support for [Koin Compose](https://github.com/InsertKoinIO/koin/blob/7c1c8712a46fd8bbe72f568bab3a2124b2ed7b5e/compose/koin-compose/build.gradle#L7-L20) for now, which is the dependency for precompose-koin.

Hi
Checkout this branch
https://github.com/InsertKoinIO/koin/tree/3.6.0-wasm

**Comment by Phaestion** [comment]
Hi @Tlaster! 

[3.6.0-wasm-alpha2](https://github.com/InsertKoinIO/koin/releases/tag/3.6.0-wasm-alpha2) has been tagged and looks like they fixed the issue of the missing `wasmJs` declaration in the [koin-compose module's build.gradle.kts](https://github.com/InsertKoinIO/koin/blob/3.6.0-wasm-alpha2/projects/compose/koin-compose/build.gradle.kts#L20)

This seems to be available in Maven Cental already https://repo1.maven.org/maven2/io/insert-koin/koin-compose/3.6.0-wasm-alpha2/

**Comment by Tlaster** [comment]
Well there's a new release [1.6.0-beta01](https://github.com/Tlaster/PreCompose/releases/tag/1.6.0-beta01) that you can try with wasm.

**Comment by reginaldlouis** [comment]
Hi,

I don't know if it's realistic or doable, but can the `Navigator` can be control also by the url in the browser? I want to be able to enter `http://www.mydomain/some_page` and be directed to the right page.
