### ISSUE TITLE
Error: No StateHolder provided

### ISSUE THREAD

**Issue by heiha100** [Tlaster/PreCompose#70]
I try put ViewModels in share module, and put compose code in androidApp. When the app is going to running, it's encounter a crash with error: java.lang.IllegalStateException: No StateHolder provided.
Here is my code:
```
@Composable
// androidMain module
fun InboxScreen(navigate: (chatId: String?, newChat: NewChat?) -> Unit) {
    val viewModel = viewModel(InboxViewModel::class) {
        InboxViewModel()
    }
}

// shared module
class InboxViewModel : ViewModel() { ... }
```

**Comment by Tlaster** [comment]
Please ensure you're following the [setup guide](https://github.com/Tlaster/PreCompose/blob/b9cf4129fcd061cfda56fa4aa644c05f952f9220/docs/setup.md) to setup your project.

**Comment by heiha100** [comment]
> Please ensure you're following the [setup guide](https://github.com/Tlaster/PreCompose/blob/b9cf4129fcd061cfda56fa4aa644c05f952f9220/docs/setup.md) to setup your project.

Oh, my bad. I ignored the step of replacing Activity and setContent. Thank you for your guide and job.

**Comment by Tlaster** [comment]
close as inactive
