### ISSUE TITLE
Dialog Scene

### ISSUE THREAD

**Issue by mahramane** [Tlaster/PreCompose#72]
Hi
Is it possible to add dialog scene?
It means that it should be exactly the same as the scene, but it should be displayed like a dialog.
For Example you can use popup for compose multiplatform instead of AlertDialog.

@Composable
fun Dialog(
    barrierColor: Color = Color.Black.copy(alpha = 0.5f),
    onDismissRequest: (() -> Unit),
    content: @Composable () -> Unit
) {
    MyBackHandler {
        onDismissRequest()
    }
    Popup(onDismissRequest = onDismissRequest) {
        Box(
            modifier = Modifier
                .clickable(
                    onClick = { onDismissRequest() },
                    indication = null,
                    interactionSource = remember { MutableInteractionSource() }
                )
                .background(barrierColor).fillMaxSize(),
            contentAlignment = Alignment.Center
        ) {
            content()
        }
    }
}

**Comment by Tlaster** [comment]
There is a [dialog function](https://github.com/Tlaster/PreCompose/blob/2f384a0fe06dc78e41c184cbac209747b9ee8857/precompose/src/commonMain/kotlin/moe/tlaster/precompose/navigation/RouteBuilder.kt#L67) in RouteBuilder an you can use it.

**Comment by mahramane** [comment]
What about BottomSheet?

**Comment by Tlaster** [comment]
For BottomSheet, you can also use the dialog function, it's just something that floats on top of your scene.

**Comment by Tlaster** [comment]
close as inactive, reopen if you still have the issue.
