### ISSUE TITLE
Switch from buildSrc to version library

### ISSUE THREAD

**Issue by TheronRogers** [Tlaster/PreCompose#79]
I have a branch in my fork that has a mostly working implementation of libs.versions.toml in place of the buildSrc module. This would enable automatic version updates via dependabot. I'm thinking this would be very helpful with keeping up with the various dependencies as many of them are changing rapidly.

I'm looking to prepare a PR for this based on any build fixes that are going in right now. Please let me know if there is interest in this or if we have reasons not to make that switch.

**Comment by Tlaster** [comment]
libs.versions.toml is now the recommend way to manage dependencies, I do want to switch to it as well as migrating the iOS project to new project structure, any pr is welcomed if you're will to contribute.
