### ISSUE TITLE
Provide guidance on contributing

### ISSUE THREAD

**Issue by TheronRogers** [Tlaster/PreCompose#80]
It would be great to have a documentation that helps contributors know what is expected from their PRs or what will help streamline integration of any proposed changes. One thing I found when working on this recently was running `./gradlew spotlessApply` before a PR. Please let me know if there's anything else that would help and I'll put together some guidance.

**Comment by TheronRogers** [comment]
Also using the `assemble` command to verify the build outside of project targets.

**Comment by Tlaster** [comment]
A contributing guide is definitely nice to have, I'll add it soon.
