### ISSUE TITLE
Is lifecycle also handled in iOS with StateFlow ?

### ISSUE THREAD

**Issue by gastsail** [Tlaster/PreCompose#98]
Loving so far the lib, I'm about to start using it, my quick question is the following.

On this example https://github.com/Tlaster/PreCompose/blob/master/docs/sample.md#greetings-app-with-viewmodel-in-100-lines

We are using `val name by homeViewModel.name.collectAsStateWithLifecycle()` which is nice for android as lifecycle aware state for the view.

My question is how is this handled on iOS, I know we need to replace the `UIWindow.rootViewController` to `PreComposeApplication`

but that will be enough to collect state as lifecycle aware equal to android ?

If so, this is great !

**Comment by gastsail** [comment]
And how about screens lifecycle, like going to another screen while state is still producing

**Comment by Tlaster** [comment]
As I understand it, the only difference between `collectAsStateWithLifecycle` and `collectAsState` in Android is that when the app goes to the background, `collectAsState` will still collect the flow, `collectAsStateWithLifecycle` will not, and both will stop collecting the flow if the composable function is not in the composable tree, so in iOS you don't need a `collectAsStateWithLifecycle` to collect a flow, just use `collectAsState`.

**Comment by gastsail** [comment]
Hmm , but Im talking that Im doing the collectWithLifecycle on iOS too because the code is in the shared module which contains the same composables for both platforms

**Comment by Tlaster** [comment]
Yes, it's still ok to use something like `collectAsStateWithLifecycle` in your app for a multiplatform project to optimize performance in Android, and the Compose itself will handle most of the lifecycle stuff for the other platform.
Personally, I don't use `collectAsStateWithLifecycle` that much even in Android, since my app only produces states when the user interacts with it.

**Comment by gastsail** [comment]
Cool, thanks a lot for your time !

**Comment by Tlaster** [comment]
close as inactive
