### ISSUE TITLE
Can't use viewModelScope

### ISSUE THREAD

**Issue by vadhmln** [Tlaster/PreCompose#99]
First of all, thanks for the great job. I think, it'll be a future of multiplatform. Anyway, my problem is when I want to use: viewModelScope.launch { }, I can't do that. I can manually import "import moe.tlaster.precompose.viewmodel.viewModelScope" but "viewModelScope" still in red color. So, if you have any thoughts it'll be welcome.
![image](https://github.com/Tlaster/PreCompose/assets/12336498/0c551726-cd37-4930-984a-5efe3e71e9ff)
And it isn't in the tip window:
![image](https://github.com/Tlaster/PreCompose/assets/12336498/84fba797-353f-47b6-8c64-a58903359d7a)

**Comment by Tlaster** [comment]
You have to use `viewModelScope` inside a class that inherit from `ViewModel`, just like the Jetpack ViewModel.

**Comment by vadhmln** [comment]
I see now. Thank you!
